### ISSUE TITLE
Infection loadouts wont work and cause an internal error

### ISSUE THREAD

**Issue by Wontedyew15** [AddstarMC/Minigames#101]
Hey so basically i created a minigame of 'infection' and it all was working fine... until i create a loadout which then caused an error message saying 'an internal error occured'. When i have the default loadout untouched only it works again. Please can you help with my problem 👍

**Comment by jupiter1390** [comment]
what was loadout's name

**Comment by Narimm** [comment]
You will need to attach the server.log report that contains the error message for us to attempt to review this..also attach the config that causes an error

**Comment by Narimm** [comment]
With no further information  I am closing this issue
