### ISSUE TITLE
Loadouts through regions Suggestion

### ISSUE THREAD

**Issue by RedJambo123** [AddstarMC/Minigames#102]
Hey, I have another suggestion for you.

I am currently trying to force to players to equip a loadout when they enter a certain area if they have a certain item in their inventory, (there are reasons why I am doing this that I would be happy to tell you if it would help, but would prefer not to do so publicly).

Anyways.... The issue that I am currently having is that doing this through regions, will not equip the players with the loadout until the next time that they respawn, whereas using the sign method I have the choice to either equip the loadout straight away or at the next respawn. Would this be something that is possible to do through regions? Maybe add it as a selector in the same GUI as where you choose the Loadout name?

Also if you are up for it, id like to chat to you about a private project I have coming up. (Feel free to remove this last sentence if you would like :) )

**Comment by Narimm** [comment]
Please test and Update if the new feature does what you require.

**Comment by RedJambo123** [comment]
That works perfectly :D Thankyou so much for adding that so quickly!
