### ISSUE TITLE
Loadouts cause an internal error to occur

### ISSUE THREAD

**Issue by Wontedyew15** [AddstarMC/Minigames#103]
So i created an infection minigame and everything works fine, apart from the loadouts. Whenever you do /mg loadout it will cause an internal error to occur. The error message i get in my console is somewhere in these lines of code:

#14.05 19:55:17 [Server] INFO hetisgwnTJ quit Infection 14.05 19:55:16 [Server] INFO ... 15 more 14.05 19:55:16 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[CraftBukkit.jar:git-Bukkit-c19c293] 14.05 19:55:16 [Server] INFO at au.com.mineauz.minigames.commands.CommandDispatcher.onCommand(CommandDispatcher.java:181) ~[?:?] 14.05 19:55:16 [Server] INFO at au.com.mineauz.minigames.commands.LoadoutCommand.onCommand(LoadoutCommand.java:63) ~[?:?] 14.05 19:55:16 [Server] INFO at au.com.mineauz.minigames.minigame.modules.LoadoutModule.displaySelectionMenu(LoadoutModule.java:233) ~[?:?] 14.05 19:55:16 [Server] INFO Caused by: java.lang.NullPointerException 14.05 19:55:16 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111] 14.05 19:55:16 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [CraftBukkit.jar:git-Bukkit-c19c293] 14.05 19:55:16 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [CraftBukkit.jar:git-Bukkit-c19c293] 14.05 19:55:16 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [CraftBukkit.jar:git-Bukkit-c19c293] 14.05 19:55:16 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:695) [CraftBukkit.jar:git-Bukkit-c19c293] 14.05 19:55:16 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [CraftBukkit.jar:git-Bukkit-c19c293] 14.05 19:55:16 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111] 14.05 19:55:16 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111] 14.05 19:55:16 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [CraftBukkit.jar:git-Bukkit-c19c293] 14.05 19:55:16 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(SourceFile:9) [CraftBukkit.jar:git-Bukkit-c19c293] 14.05 19:55:16 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(SourceFile:37) [CraftBukkit.jar:git-Bukkit-c19c293] 14.05 19:55:16 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1155) [CraftBukkit.jar:git-Bukkit-c19c293] 14.05 19:55:16 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1295) [CraftBukkit.jar:git-Bukkit-c19c293] 14.05 19:55:16 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:629) ~[CraftBukkit.jar:git-Bukkit-c19c293] 14.05 19:55:16 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[CraftBukkit.jar:git-Bukkit-c19c293] 14.05 19:55:16 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[CraftBukkit.jar:git-Bukkit-c19c293] 14.05 19:55:16 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mg' in plugin Minigames v1.11.0-SNAPSHOT-169 14.05 19:55:16 [Server] ERROR null

i will also attach my most recent log file to this post

If any more info is needed i am able to give you more. Also if possible, you can come on the server and see what's going on for yourself.
IP: Mineflip.mc.gg

Thank you!

**Comment by Narimm** [comment]
**.also attach the config that causes an error**
