### ISSUE TITLE
Plugin will not work

### ISSUE THREAD

**Issue by Piciman** [AddstarMC/Minigames#104]
I used to use this plugin every day, as I have a small server that my friends and I play on. Just recently, I did a clean wipe of my server and deleted everything, including worlds, plugins, etc. I re-installed this plugin, but when I went to use commands to create a minigame, nothing happened. I used the /pl command to see if the plugin installed, and it indeed showed up on the list, but it was listen in red, while all my other plugins were listed in green. I tried uninstalling it then re-installing, downloading previous versions, but it's been the same every time. Hopefully you can identify the issue! Thanks!

**Comment by Narimm** [comment]
You will need to attach the server.log report that contains the error message for us to attempt to review this..also attach the config that causes an error

A complete list of running plugins..

Without this  will be closed in 2 days
