### ISSUE TITLE
Play Sound Region Action Bug

### ISSUE THREAD

**Issue by trevor1097** [AddstarMC/Minigames#105]
When trying to change the sound that plays if i double click like trying to type one in instead of scrolling through the list i get kicked and this shows up in console.

 `ERROR io.netty.handler.codec.EncoderException: String too big (was 38456 bytes encoded, max 32767)`

**Comment by Narimm** [comment]
You will need to attach the server.log report that contains the error message for us to attempt to review this..also attach the config that causes an error

**Comment by Narimm** [comment]
I will need a full server log.

**Comment by Narimm** [comment]
Closed as no log provided
