### ISSUE TITLE
Minigames team bug

### ISSUE THREAD

**Issue by jupiter1390** [AddstarMC/Minigames#107]
1. Version 1.11+ would cause error in team games: some user will not get into any teams even team isn't full
2. In lobby time, player can't choose team by sign if players are more than minplayer of the game

Will add error log later

**Comment by Narimm** [comment]
Please dont post bugs without a log...I will just close them...you can repost when you provide logs

**Comment by jupiter1390** [comment]
@Narimm Strangely, there is no error log, I only found region&node error

`늑대인간1:
  infectedPercent: 10
  loadouts:
    red:
      items:
        '102':
          ==: org.bukkit.inventory.ItemStack
          type: BEETROOT
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: §c늑대의 심장
            enchants:
              BINDING_CURSE: 1
            internal: H4sIAAAAAAAAAONiYOBkEHIsKSnKTCotSfXNT8lMy0wtKuZiYGBgZGHgCA31dPHNLy5Zuj87k+uy41oWBk6QkE9qYnHJjEwF/+C4bF42BjbH3PzSvBIHCQYw4GBgCc7JL2FgTc5ILS7hYOCFm++XmJvKIJKempdalJmsl1hSkpic7ZKYm5ieyszA6V+QWpRYkpmfBzUDrJgD5iQGBgBLJa4crAAAAA==
        '103':
          ==: org.bukkit.inventory.ItemStack
          type: SKULL_ITEM
          damage: 3
          meta:
            ==: ItemMeta
            meta-type: SKULL
            display-name: §7늑대 머리
            enchants:
              BINDING_CURSE: 1
            internal: H4sIAAAAAAAAAE2Uy7KjZBDHmZnjVM4p3Vi6dTW71MgtJGExZZEQyEe4hAAfl43F5SPcIQkQwCfRV9Clr+DCJ3JrjlrW9K77393/X/WiXzDsBfvSyLuiOF7rOC3QDHsLIuzDOqIiMlpGH9cEvfi4CNfsxyBaLx8p69NkHDEkS79gL4+hBl3bFN2esVmLhra7otsLhmFvZtizkZ4r/7Xy9jet5s9loM2JxCnX22rTnerlZZzWIuAuDH/sG5bQr10JM5XMcg5EuK7FOAnr9YpaDYtdf5Djy7iZA6M9zhkaPwNvLKi7Q7aE4UZTTOVqbi3nFI5cC1rV4bo64jdvnl32Yn8d7NgRuMNdQmQHlGXuMU3jVrhMxy2BtAPgzzlvuOE1inJZbpXGqmvzZueQTvT7sdjgEqqOi9UKtpovss39LtThqZtOkVJZMNfn+2yvaJ07ajSXWDWOZ9Se0+9ZmlbZCObuxIonh5YERxrq/BYR7Sh0ZinbY1B6Zow2ya7h0IIuGtNdVsGcwQEBs4mz9QFa3Y0ioehfG2CYm7AfTr1uroIRQeC1AxNmteASvNBz5KkJILzqhATVM89mEaoybifjjs+Okc8fIJEhKmwIXoxECh7dTlifLYmJ7aVXr0JJgv4qIO+dFq1baZjP7cDw6nbhBh5y5bojcOUiLbYLYIL4nNHDMCn+shqbJpx2gTIIlrFfnFlyp4yxvhvvpWKMayQ5ssBlJawaUaDz5rgoEyk43NULvY3FM74zW36ae/i2P6EwMcT13NhtA8AeiNV6MLXF/qgzgqOHAYceXcFOkDyX3osOLWxyOYO5ZTp7tR0s9jqAARyO29XpBgBeyz7cO5GlXU1DG/pFs2YZymb9LbVy5Q2wD1PJTNvFUb0PvbLqw5Ts7/I6keYrvFKXEh/1qftphn0B/aJDbxw0SoRvk0VIn5LA4VIt2xGaaVFKBkglyxk102+g2owB5TWBCCVvC5YgS3Kl1AeP93KN5yaVP2UaX6Qef6YeOeOayuCVOqmY+QTSexrupd4ri5tnMUlgW6mWSqqx82JIsTcvBY/9auNRTBLt4ehBqQgd2IQlzEHWEGEFC3krEZ6TEJHz0EawfDCbBlFoD30FKjgGr0zlQ99zS3lkP+tlWt9mCpeWEq/Su6CEhEyfCrQ/kWFp9UoWUpqoPritUbHVVDHPpJsBWs3C0aUsQpk2pTvpC9Xc5OpkMaqtUJ55ptUpKRQ+HNVJyB63ojUb5ortkq7tpaohsbFDfMKwGfak+iXCZspe+NGuixh7xr7m2vaaBl2LlDpK4xRd//0kT9jMsgCv1Lf2w68/Rd+9E8Mn7Pm1JCP/1v7+zV8+z/yhvsfec2XdVe0Pf/78Gr88PIyibrGnBPnRDPvq//X/OH97RhW6puH3Zd2jElWt0SAUvcOetcdD89u0rh7en3H+h4RhfwMEh9CmMwUAAA==
            skull-owner: MHF_Wolf
      potions:
        JUMP:
          amp: 1
          dur: 2000000
      team: RED
    default: {}
    blue:
      items:
        '0':
          ==: org.bukkit.inventory.ItemStack
          type: IRON_AXE
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            lore:
            - §e벌목꾼이 쓰던 도끼다.
        '35':
          ==: org.bukkit.inventory.ItemStack
          type: SHULKER_SHELL
          amount: 2
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: §9총알 보급상자
        '7':
          ==: org.bukkit.inventory.ItemStack
          type: DIAMOND_HOE
          damage: 8
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: §a리볼버§a ▪ «6»
            lore:
            - §e데미지:12/12
            - §e장전:6/1.75
            - §e특수능력:헤드샷(+8)
            ItemFlags: !!set
              HIDE_UNBREAKABLE: null
              HIDE_ATTRIBUTES: null
            Unbreakable: true
        '8':
          ==: org.bukkit.inventory.ItemStack
          type: DIAMOND_HOE
          damage: 9
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: §9샷건 Type A§9 ▪ «2»
            lore:
            - §e데미지:3(*12)/5(*12)
            - §e장전:2/1
            - §e특수능력:산탄(*12)
            ItemFlags: !!set
              HIDE_UNBREAKABLE: null
              HIDE_ATTRIBUTES: null
            Unbreakable: true
      team: BLUE
  gameOver:
    invincible: true
    timer: 10
  teams:
    RED:
      displayName: 늑대인간
      startpos:
        '0':
          x: -154.04370620580303
          y: 61.0
          z: -14.779454562357932
          world: MGM
          yaw: -145.30894
          pitch: 17.850016
    BLUE:
      displayName: 주민
      startpos:
        '0':
          x: -90.44262325467454
          y: 31.0
          z: -92.87945721158239
          world: MGM
          yaw: -299.05975
          pitch: -3.4500237
        '1':
          x: -112.25046246593931
          y: 31.0
          z: -71.72147151981052
          world: MGM
          yaw: -178.30975
          pitch: 2.6999786
  defaultwinner: BLUE
  reward-scheme: standard
  rewards: {}
  minplayers: 3
  type: MULTIPLAYER
  endpos:
    x: 0.7382789023150551
    y: 65.0
    z: 0.7382789023150551
    world: lobby
    yaw: 0.0
    pitch: 0.0
  lobbypos:
    x: -115.92094975227332
    y: 56.0625
    z: -46.20596335914022
    world: MGM
    yaw: 0.041259766
    pitch: 4.7999215
  maxplayers: 16
  scoretype: infection
  flags: []
  enabled: true
  startpos:
    '0':
      x: -114.63829804807406
      y: 39.53817952087906
      z: -80.7820329043395
      world: MGM
      yaw: 324.41147
      pitch: 6.0000014
  timer: 300
  quitpos:
    x: 0.7382789023150551
    y: 65.0
    z: 0.7382789023150551
    world: lobby
    yaw: 0.0
    pitch: 0.0
  scoreboards: {}
`
This is minigame config
Always nobody will be put into team, causing teamkills
