### ISSUE TITLE
Is there a possible timer?

### ISSUE THREAD

**Issue by MacMcMillan** [AddstarMC/Minigames#111]
Hello, I am trying to make it so that after a given time an action happens. How can I accomplish this?

**Comment by Narimm** [comment]
We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.
We monitor this thread as well, as do other users of the plugin.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC
