### ISSUE TITLE
Minigames reward not working

### ISSUE THREAD

**Issue by Dimas2801** [AddstarMC/Minigames#112]
Minigames reward only work for the first win, when the second win at the same minigame, he/she doesn't get the reward at all

**Comment by Narimm** [comment]
Minigame rewards work fine - this is a config issue unless you have an error to report...

We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.
We monitor this thread as well, as do other users of the plugin.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC

**Comment by Dimas2801** [comment]
@Narimm , may i have a personal guide from you another personal message ? i'm not understand what are you trying to tell above, maybe do you have facebook account ?

**Comment by Narimm** [comment]
Its your config...not a bug....please look for support as detailed in the above post.

**Comment by jupiter1390** [comment]
@Dimas2801
You need to set reward2 for rewards after first win
