### ISSUE TITLE
Minigame suggestion

### ISSUE THREAD

**Issue by itn117** [AddstarMC/Minigames#113]
can you add tntrun minigame?

**Comment by Narimm** [comment]
You can create TNTrun via a config..

We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.
We monitor this thread as well, as do other users of the plugin.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC
