### ISSUE TITLE
Minigames ignoring infected percent

### ISSUE THREAD

**Issue by Noahkiq** [AddstarMC/Minigames#114]
This server's running Minigames v`1.11.0-SNAPSHOT-168` and minigames seem to be ignoring the infected percentage. I've set the infected percentage for a map to 99% (and other similar percentages) using both the GUI and the `/mgm set` command, but most users still join the blue team instead of the red team.

**Comment by PugaBear** [comment]
@Narimm no explanation...?

**Comment by Narimm** [comment]
Sorry I didnt mean to close it

**Comment by jupiter1390** [comment]
@Noahkiq
This bug appeared even in MC1.8 ver but still not fixed in recent 1.12 SNAPSHOT

**Comment by Narimm** [comment]
actually I think we fixed this well @Pugabyte  did :)
