### ISSUE TITLE
Tnt not damaging blocks/players in regen region

### ISSUE THREAD

**Issue by PugaBear** [AddstarMC/Minigames#115]
Due to [this event listener](https://github.com/AddstarMC/Minigames/blob/master/Minigames/src/au/com/mineauz/minigames/blockRecorder/BasicRecorder.java#L275-L283), tnt doesn't do anything when it explodes. What is purpose of this event listener? If there is a purpose, could you please add an option to disable it? It makes minigames with tnt and a regen region impossible. Thank you!

**Comment by Narimm** [comment]
```
if(!mg.hasPlayers() && !mg.hasStarted() && mg.getBlockRecorder().hasRegenArea() && mg.getBlockRecorder().blockInRegenArea(event.getLocation())){
				event.setCancelled(true);
				break;
			}
```
I think you a misreading....it only cancells if 
1. The minigame has NO players.
2. The game has NOT started
3.  The minigame has a regenerating area - 
4.  The block is in the area that regenerates.

Why would you NOT want to cancel TNT exploding...  keep in mind ALL of the above have to be true not just 1.

**Comment by Noahkiq** [comment]
We want players to be able to use TNT during minigames to blow up other players, then have the minigame regenerate the map afterwards. Currently we have to either manually paste the map everytime the minigame ends, or not use TNT, but the whole point of the minigame is to fire TNT cannons.

**Comment by PugaBear** [comment]
@Narimm If I recall correctly, when I was using the API, `mg.hasStarted()` was not returning what I was expecting. I had to use the MinigameState or something similar (can't access source atm). Maybe this is the root of the problem?

**Comment by Narimm** [comment]
In that case I suggest you use something like plugman to prove its minigames doing the event cancel...

**Comment by PugaBear** [comment]
I don't know why you want me to use plugman, but I took the Minigames and Minigames Regions plugins out and rebooted, and TNT worked fine in the same area. We also tested adjusting the regen region to different sizes, and placing TNT on the edge of and inside the region. If the TNT was set off while in the region, it would not break the blocks, however if it exploded outside of the region, it would break blocks inside the region.

**Comment by PugaBear** [comment]
@Narimm thoughts?

**Comment by Narimm** [comment]
If you feel this is an issue - ie a bug feel free to fork and fix it...and then PR however...dont fix a bug with a config disable .... if its a bug we need to work out why its a bug and fix it

**Comment by Noahkiq** [comment]
> if its a bug we need to work out why its a bug and fix it

As @PugaBear stated earlier, this is likely caused by "`mg.hasStarted()` not returning what I was expecting."
