### ISSUE TITLE
Minigames says its already started bug.

### ISSUE THREAD

**Issue by Guynamedtim** [AddstarMC/Minigames#116]
Hi,
I run a server where I use several minigames.  When I try to do one like TDM, Infection, or CTF the game works fine.  The problem is, after the game ends no one can rejoin.  It gives the message, "This game has already started" or something even though the game just ended.  All of the other minigames work fine.

**Comment by Narimm** [comment]
We see this behaviour in some games as well - we have yet to work out why ....

**Comment by Narimm** [comment]
This may well be fixed in commit 9da7794
