### ISSUE TITLE
getPlayerData() throws NPE

### ISSUE THREAD

**Issue by PugaBear** [AddstarMC/Minigames#117]
I don't know when this started since I had a try-catch around this code, but noticed it today. using `getPlayerData()` throws a nullpointer. 

Since you _consistently_ doubt all of my bug reports, I [created a plugin](https://github.com/PugaBear/MinigamesTest/releases/tag/1.0) that you can download and see for yourself. 

All it does is [try to save the PlayerData in a variable](https://github.com/PugaBear/MinigamesTest/blob/1.0/src/me/pugabear/MinigamesTest/EventListener.java#L16).

Versions:
![image](https://user-images.githubusercontent.com/12417961/27512908-77c82820-5917-11e7-8e8b-760060ec99e3.png)

[Entire startup log](http://paste.bear-nation.net/playerdatanpe)

**Comment by Narimm** [comment]
Just to be clear I dont consistently doubt your reports....its just you dont provide enough data to chase a bug

**Comment by Narimm** [comment]
Keep in mind we use the plugin on a very regularly used server...  and we are not getting the same issues
