### ISSUE TITLE
Spigot 1.12 compatability?

### ISSUE THREAD

**Issue by Junior1544** [AddstarMC/Minigames#118]
Good day you wonderful Dev's!

I run a new Spigot Minecraft server and want to add minigames to the server...

That being said, I was pointed at this plugin as a possible solution but our servers are 1.12 and it looks like this plugin isn't compatable with this version yet?

Just hope to hear that it does work or that an update will be available soon to make it run on 1.12.

Thank you so much for your time and consideration.

**Comment by alchemistmatt** [comment]
You can find the latest development build at http://jenkins.addstar.com.au/job/Minigames/
We have been running this build for a few days now and it's working well.
