### ISSUE TITLE
Minigames prompts for updates even with latest version.

### ISSUE THREAD

**Issue by JVsGamez** [AddstarMC/Minigames#119]
I've got the most recent minigames version but it still prompts me to update. Not a big deal as it still works, so I tried to disable the notification by changing the UpdateChecker to false, however, on restarts, it resets the value to true.

**Comment by Narimm** [comment]
To change config values you need to stop the server ...change them and restart...you cannot change config on a live server. atleast not change them on disk...The config is saved into memory while the server is running,.  There is a reload config command BUT we dont suggest using it....
