### ISSUE TITLE
Chat System

### ISSUE THREAD

**Issue by ROKA611** [AddstarMC/Minigames#120]
Suggestion: would it be possible to add chat feature restricted to teams?

**Comment by jupiter1390** [comment]
I wish it was like putting Special Characters like @ at front to chat in global and normal chat would be team chat and Every team chat has Customizable(in lang file) prefix so you can distinguish team and global chats

**Comment by ROKA611** [comment]
Or like commands like /g fot global and /t for team chat

**Comment by Narimm** [comment]
This wont happen ...we use bungeechat to control all chat.
