### ISSUE TITLE
when joining minigame the server crashes

### ISSUE THREAD

**Issue by Junior1544** [AddstarMC/Minigames#121]
Hi there!

Thank you for a wonderful plugin!

I use this for a few different mini games...

I currently have spleef, tntrun and one hunger games type of game setup with this plugin.

In trying to make a second Hunger Games I followed all the same steps as for the first one but when a player tries to join it, it shows the player just stars (or rain if it's raining) and the server starts using 100% cpu usage and also the server than crashes...

I need to forcably close the server and re start it to make it work...   This all happens with just the second hunger games map (different arena and different name of the game)...

There is nothing in the server logs, they just stop.

Any suggestions or help for this?

For right now, I've disabled it but would like to bring it back up...

Thank you!

**Comment by Narimm** [comment]
You could try running timings while you start the 2nd game - it might be some sort of event monitor going nuts...but without a log or config I cant suggest much.

**Comment by Junior1544** [comment]
I can turn timings on, but once i give the command to join that mini game, it wont run any other commands at all...
there's no error in the server log, nothing, and no responces.  only thing i can do is force quit and re run the server...

**Comment by Junior1544** [comment]
Thanks for the support but I've fixed the issue myself...

It seems that I had the game lobby set to high up..  i lowered it, and it works fine now..

Thanks
