### ISSUE TITLE
Fix PreSet spleef errors need to be default spleef preset config.

### ISSUE THREAD

**Issue by Fonzee9** [AddstarMC/Minigames#122]
After getting a annoying issue which is this one right here https://github.com/AddstarMC/Minigames/issues/89 also i never edited the config at all and i got this error lets fix this problem for everyone.

Also before you say its not your config error go to this link https://www.youtube.com/watch?v=jt5NBlJC86I click newest comments and look at all the people who are complaing like why isn't this working and stuff therefore just add this fixed config to the default preset spleef config.

Pastebin for the fixed config for preset spleef: https://pastebin.com/MD3PLEYL

**Comment by Narimm** [comment]
Fixed in https://github.com/AddstarMC/Minigames/commit/4ccebcdad0374abc0e6588f4e2aa48a6c0bb228a
