### ISSUE TITLE
Some bugs about minigame regeneration

### ISSUE THREAD

**Issue by jupiter1390** [AddstarMC/Minigames#124]
I made a minigame that allows player to spawn custom horse with options like name and potion effects
to ride in in-game and set all region to regeneration area so everything will go back to default, erasing mobs spawned by player.
However, sometimes some horse would not be despawned, they got their custom options removed and appear as a normal horse. It occurs in other custom mobs too.

**Comment by Narimm** [comment]
Can you post a config file for the specified game..

**Comment by jupiter1390** [comment]
@Narimm 
Config
`검투사:
  loadouts:
    default:
      items:
        '0':
          ==: org.bukkit.inventory.ItemStack
          type: CHEST
          meta:
            ==: ItemMeta
            meta-type: TILE_ENTITY
            display-name: §f장비 선택하기§f
            blockMaterial: CHEST
        '8':
          ==: org.bukkit.inventory.ItemStack
          type: GOLD_NUGGET
          amount: 64
      potions:
        REGENERATION:
          amp: 254
          dur: 1200
        HEALTH_BOOST:
          amp: 4
          dur: 2000000
  gameOver:
    invincible: true
    timer: 10
  reward-scheme: standard
  rewards: {}
  type: MULTIPLAYER
  endpos:
    x: 0.5
    y: 65.0
    z: 0.5
    world: lobby
    yaw: 0.0
    pitch: 0.0
  regenarea:
    '1':
      x: 68.0
      y: 64.0
      z: -141.0
      world: MGM
      yaw: 0.0
      pitch: 0.0
    '2':
      x: 3.0
      y: 31.0
      z: -76.0
      world: MGM
      yaw: 0.0
      pitch: 0.0
  lobbypos:
    x: 38.41807547670457
    y: 32.0
    z: -105.59069315814722
    world: MGM
    yaw: -224.25014
    pitch: -2.8499928
  maxplayers: 12
  lives: 1
  canspectatefly: true
  flags: []
  enabled: true
  startpos:
    '0':
      x: 51.058848642924936
      y: 32.0
      z: -140.69999998807907
      world: MGM
      yaw: -358.9378
      pitch: -0.29999214
    '1':
      x: 35.88747065047141
      y: 32.0
      z: -140.69999998807907
      world: MGM
      yaw: -359.53796
      pitch: 1.6500376
    '2':
      x: 21.071704576551653
      y: 32.0
      z: -140.69852944341255
      world: MGM
      yaw: -0.2878418
      pitch: 0.300045
    '3':
      x: 3.3015430554514733
      y: 32.0
      z: -123.19591353378303
      world: MGM
      yaw: -89.38745
      pitch: -0.29994065
    '4':
      x: 3.301305939909069
      y: 32.0
      z: -108.2441794930312
      world: MGM
      yaw: -88.6376
      pitch: -0.44988605
    '5':
      x: 3.3002818748354894
      y: 32.0
      z: -93.22283606286803
      world: MGM
      yaw: -89.83734
      pitch: -0.1498806
    '6':
      x: 20.532946099337465
      y: 32.0
      z: -75.30000001192093
      world: MGM
      yaw: -177.88727
      pitch: -0.74985933
    '7':
      x: 35.836350799117724
      y: 32.0
      z: -75.30488560069352
      world: MGM
      yaw: -178.63757
      pitch: -2.0998383
    '8':
      x: 50.86595690517384
      y: 32.0
      z: -75.40365018867963
      world: MGM
      yaw: -179.38776
      pitch: -2.5498362
    '9':
      x: 68.69999998807907
      y: 32.0
      z: -93.1052114824493
      world: MGM
      yaw: -271.18774
      pitch: -0.4498204
    '10':
      x: 68.69282808649587
      y: 32.0
      z: -108.1556391600945
      world: MGM
      yaw: -271.18842
      pitch: -0.29979745
    '11':
      x: 68.69999998807907
      y: 32.0
      z: -122.84735580532293
      world: MGM
      yaw: -270.1383
      pitch: -1.6497403
  timer: 300
  spectatorpos:
    x: 36.04230542156656
    y: 37.0
    z: -108.20577635650035
    world: MGM
    yaw: -178.41559
    pitch: 60.949154
  quitpos:
    x: 0.5
    y: 65.0
    z: 0.5
    world: lobby
    yaw: 0.0
    pitch: 0.0
  scoreboards: {}
`

**Comment by jupiter1390** [comment]
@Narimm 
Region

검투사:
  regions:
    All:
      point1:
        world: MGM
        x: 3.0
        y: 31.0
        z: -141.0
      point2:
        world: MGM
        x: 68.0
        y: 40.0
        z: -76.0
      executors:
        '0':
          trigger: TICK
          actions:
            '0':
              type: SWAP_BLOCK
              arguments:
                matchtype: FENCE
                matchdata: false
                matchdatavalue: 0
                totype: AIR
                todata: false
                todatavalue: 0
                keepattachment: false
            '1':
              type: BROADCAST
              arguments:
                message: 문이 열렸습니다! 나가서 싸우십시요!
                exludeExecutor: false
                redText: false
          conditions:
            '0':
              type: MINIGAME_TIMER
              arguments:
                minTime: 239
                maxTime: 240
                invert: false
          triggerCount: 1
        '1':
          trigger: TICK
          actions:
            '0':
              type: BROADCAST
              arguments:
                message: 문이 1분 뒤 열립니다! 장비를 챙기세요!
                exludeExecutor: false
                redText: false
            '1':
              type: EXECUTE_COMMAND
              arguments:
                command: mm mobs spawn Angry_Cow 1 MGM,32,32,-108
                silent: true
          conditions:
            '0':
              type: MINIGAME_TIMER
              arguments:
                minTime: 299
                maxTime: 300
                invert: false
          triggerCount: 1

**Comment by Narimm** [comment]
Outdated build please try the latest and recheck and reopen of still causing issues
