### ISSUE TITLE
PlayerPickupItemEvent WARN

### ISSUE THREAD

**Issue by andris155** [AddstarMC/Minigames#125]
`[00:24:47] [Server thread/WARN]: [Minigames] "Minigames v1.11.0-" has registered a listener for org.bukkit.event.player.PlayerPickupItemEvent on method "public void au.com.mineauz.minigames.Events.itemPickup(org.bukkit.event.player.PlayerPickupItemEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [_Razz_ Schmoller AddstarMC].`

**Comment by LazoYoung** [comment]
PlayerPickupItemEvent marked deprecated since 1.12 update by spigot.  
Should replace with EntityPickupItemEvent....

**Comment by Narimm** [comment]
Probably dont  use a version for 1.11 under 1.12..
