### ISSUE TITLE
(1.12 Snapshot)Minigames will make player win when they get score by region&node, despite not reaching max score

### ISSUE THREAD

**Issue by jupiter1390** [AddstarMC/Minigames#126]
It would end the minigame when player gets score by region&node
- would end even player get negative value score
- end message will appear every time player gets score
Seems no error log appears

Config
https://pastebin.com/jEgJ1u1R

Region
https://pastebin.com/v8T2cvU4

**Comment by LazoYoung** [comment]
You can post your config by pasting it into [pastebin](https://pastebin.com/) and link it to summarize.

**Comment by Noahkiq** [comment]
I've been having this issue too and it's broken a lot of stuff (One in the Quiver, Domination, System to show the time you took to beat a single player map, etc) - A fix for this would be really nice

**Comment by jupiter1390** [comment]
@Noahkiq
I created tag game(using juggermaut reversed and score as deathtime) and mining game(no explanation needed)
It worked fine until 1.11 but now it has been broken :(

**Comment by jupiter1390** [comment]
@Narimm 
This bug doesn't appear in build 190

**Comment by Narimm** [comment]
Okay but it re appeared in 191?

**Comment by jupiter1390** [comment]
@Narimm 
Just tested build 192
In build 192, some minigames dont have error and some has error
Will paste config later

**Comment by Narimm** [comment]
I dont need your configs... if there is an error post the stacktrace.

**Comment by Narimm** [comment]
To be honest we never really created regions with this in mind so I am not suprised it doesnt work...I am and not really going to spend time fixing something we dont use.  If you want to fix it feel free to PR

**Comment by jupiter1390** [comment]
@Narimm 
Seems no error logs appear while minigame ends

**Comment by Narimm** [comment]
Try running Whatis http://jenkins.addstar.com.au/job/WhatIs/  - this plugin allows you to track everything ...
ie /whatis eventmonitor  <event> <ticks>
you can tab complete to show all registered events that you can monitor ... it will then dump a report onto the server to help with debugging...

**Comment by Noahkiq** [comment]
Could this be related to [this line?](https://github.com/AddstarMC/Minigames/blob/ac20e7afb3073129017a9ff0641a767724dad71c/Regions/src/main/java/au/com/mineauz/minigamesregions/actions/AddScoreAction.java#L71) I believe the `>=` in the linked line should actually be `<=` (which would make it the same as [this line](https://github.com/AddstarMC/Minigames/blob/ac20e7afb3073129017a9ff0641a767724dad71c/Regions/src/main/java/au/com/mineauz/minigamesregions/actions/SetScoreAction.java#L68))

**Comment by Narimm** [comment]
Otherway round
`		if(player.getMinigame().getMaxScorePerPlayer() <= player.getScore() || player.getTeam().getScore() >= player.getMinigame().getMaxScore()){` 
is ithe wrong one thanks for pointing it out.  it is supposed to be checking that the player has won.

**Comment by Noahkiq** [comment]
Are you sure? Just tested this with @Pugabyte and my suggestion fixed the issue.

**Comment by Pugabyte** [comment]
You're saying 
```if (10 is greater than than or equal to 3) {
    end the game
}```
that's always gonna be true

**Comment by Noahkiq** [comment]
^ yeah, you're currently checking if the maximum score a player needs to win is greater than or equal to the player's current score. This is always going to be true, so the game's always going to end whenever a player gets a point.

**Comment by jupiter1390** [comment]
@Noahkiq 
Even it ends even player gets minus value score
