### ISSUE TITLE
(1.11~1.12 SNAPSHOT)Team would break to specific players

### ISSUE THREAD

**Issue by jupiter1390** [AddstarMC/Minigames#127]
Specific players would get their team breaked - not showing team color names(white nickname on scoreboards), not associated to team(even though they have team specific loadouts), even team-kill allowed

This bug appears on every type of minigame I created, even infection preset in plugin file
Players do not appear to get team-break at first but as they play many minigames they would get team-break error

+ Clearing minigames sqlite DB worked for a while, but it was temporary and still gets some bug

**Comment by Narimm** [comment]
Unless you can provide me with a specific setup where this occurs consistently then I am closing this off as not reproducible - we have never had this issue on our servers_

**Comment by jupiter1390** [comment]
# 
# Whether the plugin should check for updates

saveInventory: false
requireEmptyInventory: false
treasurehunt:
  waittime: 3600
multiplayer:
  waitforplayers: 60
  startcountdown: 5
  timerMessageInterval:
  - 900
  - 600
  - 300
  - 60
  - 30
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1
  floordegenerator:
    time: 30
  ctf:
    flagrespawntime: 60
disabledCommands:
- home
broadcastCompletion: true
playSounds: true
regeneration:
  maxDelay: 10
updateChecker: true
lang: ko_KR
backend:
  type: sqlite
  host: lazocraft.ddns.net:8081
  database: minigames_database
  username: mc6
  password: d3c9035a3d
  useSSL: false
tool: BLAZE_ROD
warnings: true
outputCMDToFile: true
minigames:
- 개싸움
- 클래시마인
- 데스태그
- 슬로우모션
- 히로빈
- 봇연습
- 검투사
- TNT태그1
- 늑대인간1
- 피라냐
- 해적선
- 골드러시
- 스플리프1
- 스플리프2
- 블라인드샷
- 웨스턴듀엘
- 묘지
- 더랩
debug: true

Using almost basic setup

**Comment by jupiter1390** [comment]
@Narimm 
What setup do you mean? config.yml?

**Comment by Narimm** [comment]
Im would suggest you snapshot the db when its working then compare it once it breaks and find the differences....once you know that you can let me know...we use mysql and dont get this issue

**Comment by Narimm** [comment]
Closing as not reproducible
