### ISSUE TITLE
Error on executing commands when adding teams

### ISSUE THREAD

**Issue by AhRoon** [AddstarMC/Minigames#129]
Hello, When I try to use /mgm set TDM_Dust team add red, It shows an error.
Using Server Version: 1.7.10 Thermos

Logs:
https://pastebin.com/01T1Vxp2

Can you fix this issues? Thanks.

**Comment by jupiter1390** [comment]
You are using latest version of minigames, It isn't compatiable with 1.7.10

**Comment by AhRoon** [comment]
Ohh, You were korean? Wow. So what version should I use?

2017. 8. 10. 오전 1:31에 "발광목성인" <notifications@github.com>님이 작성:

**Comment by AhRoon** [comment]
And I'm not using Korean, Because I was going to make a International
Server. But I usually use Korean for Wiki & Rules.

2017. 8. 10. 오전 1:31에 "발광목성인" <notifications@github.com>님이 작성:

**Comment by Narimm** [comment]
This isnt for technical support...

**Comment by jupiter1390** [comment]
@AhRoon
http://jenkins.addstar.com.au/job/Minigames/161/
Maybe this would work? Couldn't find any more older versions, seems to be removed

**Comment by Narimm** [comment]
If you continue to try and provide technical support on a bug reporting forum I will remove the ability to create bug reports.
