### ISSUE TITLE
CTF game mech- stolen flags dont register with  player "hasflag" node/region setting

### ISSUE THREAD

**Issue by RealmportalMC** [AddstarMC/Minigames#131]
I set the game mechanic to CTF, and created a region. I then set that region to give points every second the player has the flag within that area.

As the title suggests, the region does not recognize the player is holding a flag if the mech is set to CTF.

I also tested it in Custom mech. it works (sort of) the flag doesnt get removed from the world- it only says in chat "<player> has stolen the Neutral Flag" and then the score increases for said team/player.

Build 194

**Comment by Narimm** [comment]
Actually it was never meant to - IE its not supported
