### ISSUE TITLE
Better documentation for how to use different region/node settings (executers, actions, conditions etc)

### ISSUE THREAD

**Issue by RealmportalMC** [AddstarMC/Minigames#133]
Self explanatory. I cant find any documentation anywhere on using a lot of these region and node settings

for example, i cant figure out for the life of me how to teleport a player to another section of the map when they enter a region.

and yes. i have used the wiki, google, trial and error etc. with no success

**Comment by Narimm** [comment]
I am sorry but the only place for support is the spigot discussion list - this is reserved for bugs or issues that are code based.
