### ISSUE TITLE
Using playername as string

### ISSUE THREAD

**Issue by EvilZone36** [AddstarMC/Minigames#137]
Hello,
I want to set reward command or command to execute in region where is player name or executing entity. But no one strings or placeholders hasn´t worked yet.
I read https://github.com/AddstarMC/Minigames/issues/93 but in console I got error "player not found".
Can you add to next version of you excelent plugin string @s (to target executing entity like cmd block)?
I also tried to use mycmd but mycmd dont know executing entity from  Minigames plugin. It must be typed from Minigames directly.
Thank you and have a nice day,

**Comment by Narimm** [comment]
minigames is simply executing a command as console 
[see here](https://github.com/AddstarMC/Minigames/blob/e3b30d079fbed53687c6755a89adaad47a4d3572/Minigames/src/main/java/au/com/mineauz/minigames/minigame/reward/CommandReward.java#L38-L39)

Any command you can execute at console should be possible...review your logs

**Comment by EvilZone36** [comment]
```
[17:33:31] [Server thread/INFO]: CONSOLE issued server command: /give %player% stone 5
[17:33:31] [Server thread/INFO]: [0;31;1mError: [0;31;1mPlayer not found.
```

**Comment by Narimm** [comment]
Well for starters the command we have discussed above is regarding the REWARDSMODULE not Minigame regions - 

If you had read the code regarding that module you would have seen  that it uses a different set of replacers 
https://github.com/AddstarMC/Minigames/blob/338470191194086e1d65e590be1291c0fe7dc311/Regions/src/main/java/au/com/mineauz/minigamesregions/actions/ExecuteCommandAction.java#L63-L78
