### ISSUE TITLE
Not able to break blocks

### ISSUE THREAD

**Issue by alandioda** [AddstarMC/Minigames#138]
I wanted to make a spleef minigame with the plugin, but while in the game i am unable to break enything. 

I have tried enything but it doasn't want to work.
And for some reason i can't pick gamemechanic spleef.
/mg set test gamemechanic race
/mg set test gamemechanic spleef

this command works:
/mg set test gamemechanic ctf

I am using 1.8.8 bukkit server and minigames for 1.8

Other than that I love this plugin and the complex games that you can create!
Please tell me if i am doing something wrong.
Thanks!

**Comment by Narimm** [comment]
We dont provide support or trouble shooting for outdated servers...please update Spigot to 1.12 and use the latest version

**Comment by alandioda** [comment]
Hi! I just updated to the last version minigames 1.12.0 and am running bukkit 1.12.1 server, and it still doasn't work!
Why not?
Thanks!

**Comment by Narimm** [comment]
You will need to attach the server.log report that contains the error message for us to attempt to review this..also attach the config that causes an error

We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.
We monitor this thread as well, as do other users of the plugin.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC
