### ISSUE TITLE
Block breaking doesn't work

### ISSUE THREAD

**Issue by Fonzee9** [AddstarMC/Minigames#140]
https://github.com/AddstarMC/Minigames/issues/138

Same exact problem i have blocks whitelisted and i can't break them... i have tried everything this is a severe problem with this plugin i want to use it but with block breaking not working i can't please fix it for everyone..

I haven't seen console errors it's just not working..

**Comment by Fonzee9** [comment]
Also i am on Spigot 1.12.1

**Comment by Narimm** [comment]
Please install this plugin http://jenkins.addstar.com.au/job/WhatIs/

First run `/whatis whatcancelled event blockbreak 600`
Ensure the message when you try to break a normal (unbreakable block is ```
[15:33:10] [main/INFO]: [CHAT] Handler: [HIGH] au.com.mineauz.minigames.blockRecorder.BasicRecorder.blockBreak(BlockBreakEvent)
```
once your an op and in a minigame use the command `/whatis eventmonitor blockbreak 600`

You will get a  report saved on the server copy the out put here as a pastebin with your config

**Comment by Narimm** [comment]
Please install this plugin http://jenkins.addstar.com.au/job/WhatIs/

First run ` /whatis whatcancelled event blockbreak 600 `  tab completion will work to find events.
Ensure the message when you try to break a normal (unbreakable block) then try and break a block that SHOULD be breakable 
Both should output the following
```
[15:33:10] [main/INFO]: [CHAT] Handler: [HIGH] au.com.mineauz.minigames.blockRecorder.BasicRecorder.blockBreak(BlockBreakEvent)
```
once your an op and in a minigame use the command /whatis eventmonitor blockbreak 600
You will get a report saved on the server in the directory `plugins/whatis/reports` copy the out put here as a pastebin with your config as well for the game in question

**Comment by Fonzee9** [comment]
As i was using /whatis report it did an error... https://pastebin.com/2Rxstbmn

That plugin is outdated to use tests on :(

**Comment by Fonzee9** [comment]
My spleef config https://pastebin.com/dTfhbSjU

as you can see i have snowblocks whitelisted to be broken but i can't break it whitelistblocks:
  - SNOW_BLOCK
  whitelistmode: true

**Comment by Fonzee9** [comment]
Found a fix for this :)

Type this /minigame set name gamemode survival
