### ISSUE TITLE
Region and Kits

### ISSUE THREAD

**Issue by Welost** [AddstarMC/Minigames#142]
Can i create a region where we can change kits without need to suicide ?
Please answer me !

**Comment by Noahkiq** [comment]
@Welost yes, yes you can. iirc, it's in the `Minigame Actions` -> `Equip Loadout`, then enter loadout name and enable option to automatically equip it

**Comment by Narimm** [comment]
We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.
We monitor this thread as well, as do other users of the plugin.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC
