### ISSUE TITLE
Start/EndMinigameEvent called twice

### ISSUE THREAD

**Issue by Pugabyte** [AddstarMC/Minigames#145]
I'm listening to the [StartMinigameEvent](https://github.com/AddstarMC/Minigames/blob/master/Minigames/src/main/java/au/com/mineauz/minigames/events/StartMinigameEvent.java) to move people around in Discord voice chats when the game starts. However the event is being called twice, so this happens: 
![](https://i.imgur.com/j29WhpH.png)

This was happening at first, then it stopped for a bit, then it started happening again. 

Possibly related to #116?

**Comment by Pugabyte** [comment]
I was starting it in the same manner, with the same players, in the same game, without restarting the server or the code or anything.

![](https://i.imgur.com/70kna69.png)

**Comment by Narimm** [comment]
Pug do you have http://jenkins.addstar.com.au/job/WhatIs/ installed

**Comment by Pugabyte** [comment]
Yes

`/whatis event handlers StartMinigame`

![](https://i.imgur.com/OdFBpA1.png)

`whatis eventmonitor StartMinigame 160`

![](https://i.imgur.com/a1i5IWE.png)

http://paste.bear-nation.net/minigameevents

**Comment by Narimm** [comment]
@Pugabyte Can I just confirm in the game in question you are teleporting the player on wait ...and also teleporting the player again on start?

**Comment by Pugabyte** [comment]
Yes. they move from the main lobby to the game's specific lobby then into the map.

**Comment by Pugabyte** [comment]
@Narimm This seems to break it completely. I joined a minigame with one other person and executed /mgm start <minigame>. The start of game effects were applied (blindness in this case), and my plugin did catch a StartMinigameEvent, but we were not teleported into the map and were not assigned teams. No error was thrown either.

Executing `/mgm quit` [threw an error](http://paste.bear-nation.net/calet.vbs) (but still called the EndMinigameEvent as well)

(I'm reverting back to the previous version, so you won't be able to test on my server)

**Comment by Narimm** [comment]
No drama I am testing it on our test server anywa

**Comment by Narimm** [comment]
Closed as fixed in 9364015
