### ISSUE TITLE
Setting New Minigames

### ISSUE THREAD

**Issue by GAPUniverse** [AddstarMC/Minigames#147]
On a server I'm running I have the minigame plugin installed.
I've only got one problem.
When I want to make a new map I can't edit it through chat.
for example: I do /minigame edit (Name of map), Then I get send to the menu with options, When for example I go to team options and want to add a new team I have to type the name in the chat.
When I do that I literally type it in the chat and the plugin doesn't recognize it.
I think it has something to do with a bungeecord plugin I'm using (FreeBungeeChat for chatting across server’s).
Is there a way it can be fixed?

**Comment by Narimm** [comment]
We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.
We monitor this thread as well, as do other users of the plugin.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC
