### ISSUE TITLE
[Request] Add command to remove a player's time from a map

### ISSUE THREAD

**Issue by noellekiq** [AddstarMC/Minigames#150]
Because of a separate (patched) MGM plugin issue, several players now have 0 second time on parkour maps, ruining the statistics. A command to remove all of a player's times for a certain map would be nice for situations like this. (ie `/mgm cleardata Noahkiq ParkourMap`)

**Comment by Narimm** [comment]
So you want a command to clear a specific players history for a specific game?

**Comment by Narimm** [comment]
Keep in mind that will also reset rewards

**Comment by Noahkiq** [comment]
Yeah, that's what I'm requesting. Not sure what rewards you're talking about, though.

**Comment by Narimm** [comment]
Generally when games award a reward (well atleast how we set them up the first reward is higher and subsequent rewards are reduced (ie in game cash)

**Comment by JustSteveThings** [comment]
We've not given rewards in our mazes and parkour's so it wouldn't be an issue. Other then going to the mini-game deleting it and setting it back up is there anywhere in the files i could just remove everyone's stats for that map?

**Comment by Narimm** [comment]
yep you can just use mysql to access the db and delete the player stats there

**Comment by Narimm** [comment]
To remove a specific player you would need the UUID
then do
`mysql>DELETE FROM PlayerStats where player_id='<PLAYERUUID>' and mini game_id='<gameID>' `

**Comment by Narimm** [comment]
Given the limited use this would recieve I wont be adding this command and would suggest people use MYSQL to achieve it.
