### ISSUE TITLE
Minigame has no start position

### ISSUE THREAD

**Issue by Pugabyte** [AddstarMC/Minigames#152]
[config.yml](http://paste.bear-nation.net/pepav)
[regions.yml](http://paste.bear-nation.net/oqaxe)

I can confirm that the startpos listed in the config.yml are inside the map

The files [have not been changed for 11 days](https://i.imgur.com/i2XJWmr.png), and my staff confirm that the game was played on Saturday (4 days ago). 

I recently updated from a version before the patch for #145 to the latest version as of this issue creation, so I suspect the problem lies within those commits.

This also affects one other map that we know of, but other games of the same type work fine.

**Comment by Pugabyte** [comment]
After further comparison to working games, I realized there seemed to be no game startpos, only team startpos. Doing `/mgm set KodaCove start 1` fixed the problem. Could this mean that, somewhere in #145 refactoring, you used startpos instead of lobbypos?

**Comment by JustSteveThings** [comment]
Kodacove is an infection, it shouldn't have a Start 1 Since it's a team based game it should only have a lobby, quit, end and a /mgm set kodacove start (teamcolour) e.g red 1 Additionally spectate start as well but we dont use it on infections

**Comment by Narimm** [comment]
```
else if(minigame.getStartLocations().size() <= 0 ||
                    (minigame.isTeamGame() && !TeamsModule.getMinigameModule(minigame).hasTeamStartLocations())){
                player.sendMessage(MinigameUtils.getLang("minigame.error.noStart"), "error");
                return;
            }
```

its pretty straight foward - I cant find a section where we dont allow either a normal start or a team start.

**Comment by Narimm** [comment]
Can you please confirm if you are still experiencing this issue.

**Comment by Narimm** [comment]
Outdated build please try the latest and recheck and reopen of still causing issues
