### ISSUE TITLE
/mgm quit throws QuitMinigameEvent, even if not in game

### ISSUE THREAD

**Issue by Pugabyte** [AddstarMC/Minigames#153]
![](https://i.imgur.com/e7uzRae.png)

**Comment by Narimm** [comment]
https://github.com/AddstarMC/Minigames/blob/e3b30d079fbed53687c6755a89adaad47a4d3572/Minigames/src/main/java/au/com/mineauz/minigames/commands/QuitCommand.java#L60

Shows that it specifically checks that if you're not in the game it doesn't execute....UNLESS you have a certain perm AND you use args? have you tested this and find that it occurs with NON-admin>?

**Comment by Pugabyte** [comment]
I tested with a non-admin, no args, and it still happens
