### ISSUE TITLE
Minigame_Timer does not execute

### ISSUE THREAD

**Issue by Turidus** [AddstarMC/Minigames#156]
To reproduce using 1.12.0 Minigames, 1.12 Regions and 1.12.2 Craftbukkit (Sep. 18 2017):

Create a minigame, either single or multiplayer.
Create a node and give it a Minigame_Timer_Executer
Add an action (i used Minigame/SendMessageAction)

Expected behavior: The executer gets triggered once every second (20 game ticks) and the message gets send

Observed behavior: The executer does not trigger or does not execute the action. No exceptions or errors are shown in the log

**Comment by Narimm** [comment]
I would ask you update to the latest stable build and recheck for the error.

**Comment by Turidus** [comment]
I made a clean install of the newest craftbukkit and the Minigames Pack v1.12.0-SNAPSHOT-216
(Latest build available on https://www.spigotmc.org/resources/minigames.19687/)

Minigames Region behaved in the exact same way, with no execution of the Minigame_Tick trigger and the error with the additional condition.

To be sure i did the same thing with the newest dev build v1.12.1-SNAPSHOT-224 (http://jenkins.addstar.com.au/job/Minigames/lastBuild/)

Here the condition did NOT lead to an error!

**Comment by Turidus** [comment]
I made a clean install of the newest craftbukkit and the Minigames Pack v1.12.0-SNAPSHOT-216
(Latest build available on https://www.spigotmc.org/resources/minigames.19687/)

Minigames Region behaved in the exact same way, with no execution of the Minigame_Tick trigger.

To be sure i did the same thing with the newest dev build: v1.12.1-SNAPSHOT-224 (http://jenkins.addstar.com.au/job/Minigames/lastBuild/)

The minigame_timer did still not fire. I suspect that the MinigameTickEvent is never reaching RegionEvents.

**Comment by Turidus** [comment]
On thing i noticed:

The same problem happens with GameStartTrigger

Both event handler for GameStart and MinigameTimer pass a null as player value.

If the Trigger would execute then this would lead to a host of problems with different Action classes. Some of them (like GiveItem or Broadcast) do not check if a player is null, others do but just throw the action away even if you would not expect this (like PlaySound).

But if you try to start a GiveItem action with a MinigameTimer or GameStart trigger, both do not throw the expected NullPointerExceptions.

**Comment by Narimm** [comment]
Thanks for the insight I do promise this is on my radar...just have a few other projects that I have to do first

**Comment by Turidus** [comment]
No problem at all. I just wanted to provide the maximum amount of information :)

**Comment by Narimm** [comment]
Ok looking at this issue I need a bit more debugging in your setups...there is a plugin called [Whatis ](http://jenkins.addstar.com.au/job/WhatIs/) found here...it is a debugging plugin we can use to view events and handlers in realtime.

Install it with the setups and run it has full tab completion - you can view monitor for events and they will be reported to a text file as well as view all handlers registered for an event.

**Comment by Turidus** [comment]
I will get to this. At the moment your link does not respond, preventing me from getting this plugin. Is there an alternative link? If not, I will have to wait until the server can be reached again.

**Comment by Narimm** [comment]
Outdated build please try the latest and recheck and reopen of still causing issues
