### ISSUE TITLE
Message duplicating

### ISSUE THREAD

**Issue by MiniWorks18** [AddstarMC/Minigames#158]
In version 1.12.0-SNAPSHOT-221 personal messages to players are sent twice. This is not the case in version 1.12.0-SNAPSHOT-217

**Comment by Narimm** [comment]
Hey Mini can you get a screenshot of the message dupes

**Comment by MiniWorks18** [comment]
![screen shot 2017-12-05 at 6 59 58 pm](https://user-images.githubusercontent.com/31182560/33596137-cbcf9b26-d9ee-11e7-97bc-b01f817ee442.png)

**Comment by Narimm** [comment]
....How was this message generated??

**Comment by Narimm** [comment]
I assume it was on an actionNode?

**Comment by MiniWorks18** [comment]
Yeah, using the message action inside a node. The node was triggered by a region. I've had this happen to multiple games.
