### ISSUE TITLE
Non-existant "race" minigame? + More

### ISSUE THREAD

**Issue by RicoSteves** [AddstarMC/Minigames#163]
Hello! I am running Minigames version 1.12 (newest of now) and I have loved it so far. The openness for creativity is truly great. I just have a few questions:

1. You name a "race" minigame as an option, but it is not listed in possible game mechanics. How can I make a race minigame?

2. How do you set loadouts to the infected or juggernaut specifically?

Thank you in advance!

**Comment by Narimm** [comment]
We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.
We monitor this thread as well, as do other users of the plugin.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC
