### ISSUE TITLE
No Teleportation allowed.

### ISSUE THREAD

**Issue by HyperGamerWM** [AddstarMC/Minigames#164]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report
  - [x] feature request

* **Do you want to request a *feature* or report a *bug*?**
There is no teleportation allowed and no way to configure it.
The message is:

15:49:28 | game |   | info | [14:49:28] [Client thread/INFO]: [CHAT] [Minigames] Failed to teleport. This could be related to world permissions.

* **What is the current behavior?**
I haven't been able to find any way to change the world permissions in minigame
Teleports works as expected when not in the game

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**

* **What is the expected behavior?**
No message and normal teleportaion behavior with in the minigame

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
- Spigot Version: 
- Minigames version: 1.8.0- build #

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Narimm** [comment]
We will not support a feature request based on an old version...and we will not be adding new features to old versions.

**Comment by Narimm** [comment]
Just an update you can teleport players using the internal minigame teleport commands
```				"/minigame teleport <Player> <x> <y> <z> [yaw] [pitch]",
				"/minigame teleport <Player> Start [id] [team]",
				"/minigame teleport <Player> Checkpoint",
				"/minigame teleport <Player> <Player>"````
