### ISSUE TITLE
Wiki page not working

### ISSUE THREAD

**Issue by mrblake213** [AddstarMC/Minigames#165]
The links in the spigot page isn't working

specifically the wiki page.

**Comment by alchemistmatt** [comment]
Our apologies for that.  Our web server is undergoing an extended, unplanned outage.  We hope to have the pages restored within the next 2 weeks.  If you have a specific question, ask it here and we may be able to help you.

**Comment by alchemistmatt** [comment]
Also, be sure to look over the information on the Github-based wiki:
https://github.com/AddstarMC/Minigames/wiki

**Comment by alchemistmatt** [comment]
The wiki page is now back online: http://mgwiki.addstar.com.au/
