### ISSUE TITLE
Download page for 1.12 is not working

### ISSUE THREAD

**Issue by nutella25** [AddstarMC/Minigames#166]
Hi,
The download page for 1.12 release is not found in jenkins

**Comment by alchemistmatt** [comment]
We are working on restoring that page.  In the meantime, I have updated the Github release page for 1.12 to include the .jar files for both version 1.12.0 and 1.12.1:
https://github.com/AddstarMC/Minigames/releases/tag/MinigamesProject-1.12.0

**Comment by alchemistmatt** [comment]
All download links at https://www.spigotmc.org/resources/minigames.19687/ are now working.
