### ISSUE TITLE
Why i can't set presets

### ISSUE THREAD

**Issue by Whyteeh** [AddstarMC/Minigames#167]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**

I want to request a bug report

* **What is the current behavior?**

When i try to set a preset they say "An internal error has occurred" ecc..

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**

![2018-01-15_15 10 55](https://user-images.githubusercontent.com/35457852/34946246-6aafa2ea-fa06-11e7-996f-9e67dfe09b31.png)

![2018-01-15_15 10 57](https://user-images.githubusercontent.com/35457852/34946251-705e4f48-fa06-11e7-8160-45b64e0c3ee3.png)

* **What is the expected behavior?**

They should be set the preset

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
- Spigot Version: 
- Minigames version: 1.12.1- build #

Spigot 1.12
* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Narimm** [comment]
To assist with diagnosis: 

You will need to attach the server.log report that contains the error message for us to attempt to review this..also attach the config that causes an error (use pastebin).  If there is no error...please attach a server.log that shows spigot version/ minigames version and the log file when the issue occurs with `/minigame debug` active

Sincerely
AddstarMC Admin

**Comment by Whyteeh** [comment]
Hi,i have another problem..when i start a race minigame my server lags/crashes...why?

**Comment by Narimm** [comment]
We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.
We monitor this thread as well, as do other users of the plugin.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC
