### ISSUE TITLE
Preset

### ISSUE THREAD

**Issue by ActiveBaby** [AddstarMC/Minigames#171]
Hi. Can you add minigame preset - TDM. Teams have only 5 min (or any) for have more kills than enemy team.

**Comment by Narimm** [comment]
We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.
We monitor this thread as well, as do other users of the plugin.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC

**Comment by Narimm** [comment]
I dont have time to add presets if someone wants to add one they can PR it
