### ISSUE TITLE
Actions / Play_Sound / Sound string too big 

### ISSUE THREAD

**Issue by MiniWorks18** [AddstarMC/Minigames#174]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
The plugin instantly kicks me from the server. This has happened both on AddstarMC and on my local server.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**
Create a region, create a "Player_sound" action, click the "Play_sound" action for more details, then double-click the first item in that gui page (noteblock named "Sound").

* **What is the expected behavior?**
After double-clicking, the gui is suppose to close for a limited time while you look at the list of options in chat, and type the one you want.

* **What is the motivation / use case for changing the behavior?**
It's very useful to see a list of the options when it's a large array to choose from. 

* **Please tell us about your environment:**
- Spigot Version: 
- Minigames version: 1.12.1-SNAPSHOT-217

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Console message:
2018-03-09 22:08:44 [Netty Epoll Server IO #2/ERROR]: io.netty.handler.codec.EncoderException: String too big (was 43181 bytes encoded, max 32767)
2018-03-09 22:08:44 [Server thread/INFO]: MiniWorks18 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 256)

**Comment by Narimm** [comment]
Should be fixed in dev
