### ISSUE TITLE
Unable to join Minigame 

### ISSUE THREAD

**Issue by ZeGamingCuber** [AddstarMC/Minigames#175]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... 
bug report

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
when trying to join minigame it says "this minigame type cannot use the selected mechanic!"

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**
1.Make a Minigame
2.Try to Join it

* **What is the expected behavior?**
Joining the minigame

* **What is the motivation / use case for changing the behavior?**
TO MAKE IT ACTUALLY WORK!

* **Please tell us about your environment:**
- Spigot Version: latest version of CraftBukkit for 1.12.2
- Minigames version: 1.12

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
N/A

**Comment by Castiella** [comment]
Have you tried changing the game mechanic? this happens to us a lot. /mg set GAMENAME gamemech [lives/custom/infection] ect

**Comment by Narimm** [comment]
I am closing this ...  as unable to replicate.
