### ISSUE TITLE
How to show players on [minigame] join sign?

### ISSUE THREAD

**Issue by LinsaFTW** [AddstarMC/Minigames#181]
You told me before that its possible. How? Thanks.

Yes i read the wiki like 4 times.

**Comment by Narimm** [comment]
We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.
We monitor this thread as well, as do other users of the plugin.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC
