### ISSUE TITLE
No minigame winners

### ISSUE THREAD

**Issue by DKing328** [AddstarMC/Minigames#184]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [this one] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
Report a (potential) bug. This could possibly be an issue on my end, but I can't figure out how to fix it, and didn't find anything in the wiki to help. 

* **What is the current behavior?**
When a minigame ends, the plugin doesn't seem to be broadcasting the winner, or rewarding them accordingly. I have been able to get the plugin to do so if the players physically hit a "minigame finish" sign, but minigames such as Infected, Spleef, CTF, etc., where the players win automatically are not finishing and rewarding players correctly. 

(Furthermore, we are also experiencing an issue where players will spawn in the same position when multiple start positions are set. I know this has been reported before, but it is a pretty severe bug, and I'd like to see it squashed.)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**
Spleef game that is experiencing the issue: https://pastebin.com/nd7V0zPV
Infected game that is experiencing the issue: https://pastebin.com/TJEzwWa4

* **What is the expected behavior?**
When a game ends, it should broadcast in chat "name won Spleef" or "Red team won Infected" (for example) and reward the winner(s) with the configured rewards. Right now, it is not doing that. 

* **What is the motivation / use case for changing the behavior?**
To make the games work correctly.

* **Please tell us about your environment:**
- Spigot Version: [21:07:54 INFO]: This server is running Paper version git-Paper-1399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
- Minigames version: 1.12.1- build # [21:08:11 INFO]: Minigames version 1.12.1-252

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
No errors in console when this occurs.

**Comment by Narimm** [comment]
You can try using a version from the development branch

**Comment by DKing328** [comment]
Using the latest dev build, I'm pretty sure

**Comment by DKing328** [comment]
This issue is also occurring for a simple deathmatch game I made, with a scoretype based on kills. When a player reaches the winning number, everyone leaves the game, but there's no broadcast in chat, and no rewards are given. 

I'll be happy to provide any further information you need to help fix this.

**Comment by Narimm** [comment]
https://jenkins.addstar.com.au/job/Development_Builds/job/Minigame_Dev/41/

**Comment by Narimm** [comment]
Your just usinng the latest master build

**Comment by DKing328** [comment]
Ah, alright, that version fixed the winners issue. I'll close this.

Thanks!
