### ISSUE TITLE
Many issues, hoping someone sees this

### ISSUE THREAD

**Issue by Castiella** [AddstarMC/Minigames#186]
Okay so firstly, the issue with the same start points for all players is still broken in the current development build, even though it was apparently resolved.

2ndly, new issues within the newest build:

Infection gamemode is no longer working as it used to. Now players return to the lobby once killed, rather than join the red [infected] team. Friendly fire is also enabled for some reason.

**Comment by Narimm** [comment]
Create a single issue for each bug...state the bug paste a config and in general follow the template provided.
