### ISSUE TITLE
NoClassDefFoundError (ComparableVersion)

### ISSUE THREAD

**Issue by DracarysPro** [AddstarMC/Minigames#189]
Cannot load the RC version of Minigames (Build 257): https://pastebin.com/U07ntdf7

Likely caused by this commit: https://github.com/AddstarMC/Minigames/commit/1ef21b545796d9bbaccdd27d142fbb08a34483dd

**Comment by Narimm** [comment]
Cheers Drac....wierdly I didnt get this locally..so I can only I assume some other jar has that class on the small test server...thanks for the report

**Comment by Narimm** [comment]
Should be fixed in the latest build test please  - it was because we run paper which has that class.

**Comment by DracarysPro** [comment]
Now it works if restarting, but does not work if loading with plugman (_java.lang.NoClassDefFoundError: Could not initialize class au.com.mineauz.minigames.Minigames_) . Before the latest release, it worked even with plugman.

**Comment by Narimm** [comment]
....Plugman should not be used to load plugins period...doing so will never be supported...

**Comment by Narimm** [comment]
That being said you can post the error and I will take a look

**Comment by Narimm** [comment]
No update so closing
