### ISSUE TITLE
Players unable to join team when nick named.

### ISSUE THREAD

**Issue by creatorfromhell** [AddstarMC/Minigames#192]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [X] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
Refer to I'm submitting a... above.

* **What is the current behavior?**
Player's with nick names aren't properly assigned a team. When they click on a team's sign their name stays white in the Scoreboard, and when the game starts they are able to hit both teams.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**
Use essentials to get a nick name, then attempt to join a team.

* **What is the expected behavior?**
To have the player be assigned to the team they selected, nick name or not.

* **What is the motivation / use case for changing the behavior?**
To make team selection actually work with a common server functionality.

* **Please tell us about your environment:**
- Spigot Version: 1.12.2
- Minigames version: https://www.spigotmc.org/resources/minigames.19687/update?update=206582

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Narimm** [comment]
Outdated build please try the latest and recheck and reopen of still causing issues
