### ISSUE TITLE
Teleport issues

### ISSUE THREAD

**Issue by AfkF24** [AddstarMC/Minigames#195]
So basically, I've been having this weird issue for a while now where players wouldn't get teleported from the waiting lobby to the arena on game start. It happens completely randomly, and absolutely no errors nor warnings show up in console. (Players get their items and everything, but don't get teleported)
At the same time, players often don't get teleported out of the arena on game end, and just stay there.

No other plugins of mine have this issue, so I'm assuming it's probably Minigames-related. I may be completely wrong though. Can any other plugin users relate to this?

- Spigot Version: 1.12.2- build 1533
- Minigames version: 1.12.1- build 258

**Comment by Schpammer** [comment]
Could be same as Issue #191

**Comment by AfkF24** [comment]
Yup, looks the same. Are you experiencing teleport issues upon game ending as well?

**Comment by Schpammer** [comment]
Nope, teleportation to End/Quit positions working as they should.

**Comment by Schpammer** [comment]
Hey, can you validate if your problem is fixed by the latest commit? 0b4e9d40f5bc88b5930ac0094d7f403bde3fc55a

**Comment by AfkF24** [comment]
Did some more testing and haven't had a single issue!
Teleporting out of the arena on game end might have been caused by my Combat Logger plugin, preventing teleports for players in combat. Will keep an eye on that.

Thanks for the fix @Schpammer

**Comment by Schpammer** [comment]
Ocassionally in one minigame? Maybe it's something with the gamemode.

Do you know, if the game before was finished or quitted?

**Comment by AfkF24** [comment]
> Ocassionally in one minigame? Maybe it's something with the gamemode.
I think it happened in multiple minigames, but doesn't happen too often. That's what I've been told at least

> Do you know, if the game before was finished or quitted?
No info on this, but can try to get some additional insight

**Comment by AfkF24** [comment]
Okay, so, the issue seems to be only happening with this one minigame that uses "lives" as scoretype. I can't really find any other differences from other minigames, other than that one.

If the players quit the game once it's started and re-join, they get teleported to the play area the second time.

**Comment by Narimm** [comment]
Outdated build please try the latest and recheck and reopen of still causing issues
