### ISSUE TITLE
Infection issues.

### ISSUE THREAD

**Issue by Castiella** [AddstarMC/Minigames#196]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [x ] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

Infection is not working properly.
One of my games randomly broke using the recent (stable) jenkins build. When players join the game, it starts correctly, however survivors can attack each other. When a zombie kills a survivor, rather than the person joining the zombies, they are removed from the game entirely.

Thinking maybe it was bugged, i deleted the game and made a new one, following the WIKI word by word. However, once i got to set the start positions up, it constantly told me that blue team did not exist. (I also tried zombies & survivors) I made sure it was set up correctly, and it was. I'm therefore not sure why this is happening.

* **What is the expected behavior?**

Players should not be able to kill people on their team and should join zombies when killed.

* **Please tell us about your environment:**
- Spigot Version:  1.12.2
- Minigames version: 1.12.1- build # Build #258

**Comment by Castiella** [comment]
Also want to add, when i create the teams with /mg set infection teams ect

The positions work, however again, we can teamkill and the same thing happens in the old game -when you die you get sent to the lobby rather than zombie spawn

**Comment by Narimm** [comment]
Unless they are on spigot they are not stable builds they are all development...and currently I am not working on 1.12 at all any bugs wont be fixed until a 1.13 release

**Comment by Narimm** [comment]
Outdated build please try the latest and recheck and reopen of still causing issues
