### ISSUE TITLE
Lobby issue

### ISSUE THREAD

**Issue by Nockon** [AddstarMC/Minigames#197]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
 bug report 

* **Do you want to request a *feature* or report a *bug*?**

Bug report

* **What is the current behavior?**

I just set up Spleef arena when i get players to join, the countdown gets stuck on 4 or 5 secs
 and just repeats it. if tried dropping the countdown timer in the config bellow this but on reload/restart it goes back to 10 sec countdown timer

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**

http://prntscr.com/kkvtdo

* **What is the expected behavior?**

The count down is ment to carry on and game start

* **What is the motivation / use case for changing the behavior?**

Want plugin to work 

* **Please tell us about your environment:**
- Spigot Version:  spigot 1.13
- Minigames version: 1.12.1- build # Minigames-Pack-1.12.0-SNAPSHOT

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by ignius01** [comment]
I have the same issue, glad to see its not just me.

**Comment by Narimm** [comment]
Outdated build please try the latest and recheck and reopen of still causing issues
