### ISSUE TITLE
Game never starts, countdown issue

### ISSUE THREAD

**Issue by ignius01** [AddstarMC/Minigames#199]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [X] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
Bug!

* **What is the current behavior?**
When players join a minigame, it never starts, and timer never ends, ex.
[Minigames] You have started a ...
[Minigames] 5sec
[Minigames] 4sec
[Minigames] 4sec
[Minigames] 4sec
[Minigames] 4sec
[Minigames] 4sec
[Minigames] 4sec

It always gets stuck at the number directly below the start time (Ex. if its 10 second start time it counts down 10, 9, 9, 9, 9...)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**
For players they just type /mg join -minigame name-

I can provide a screenshot, but theres not much to take a picture of.

* **What is the expected behavior?**
The minigame starts, and it doent just keep saying "[Minigames] 4sec"

* **What is the motivation / use case for changing the behavior?**
So it works, haha.

* **Please tell us about your environment:**
- Spigot Version:
 1.13

- Minigames version: 1.12.1- build #

Minigames-1.12.2-RC 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Lmk if you need more information. This is everything i think could be helpful.

**Comment by Narimm** [comment]
Outdated build - test the new build and make a new one if the issue persists
