### ISSUE TITLE
Scoreboard Signs Not Updating 1.13

### ISSUE THREAD

**Issue by delbertina** [AddstarMC/Minigames#204]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
Scoreboards do not update. Player wins a minigame like a maze and the scoreboard does not change with their time. Additionally, player changes name and scoreboard does not change even after playing the game.

Potentially might be after a restart but im not 100% sure if that is just a coincidence. Noticed that the first day a minigame was created the scoreboards would update then after some time (maybe a restart) they would not update. One of the players that was on the leaderboard before they stopped updating changed their name and it is not updating on the leaderboard either. Looking in the database, it was changed but something from the database to the signs is not working correctly. Also, all the stats are in the database so that part does not seem to be the issue.

* **Please tell us about your environment:**
- Spigot Version: Paper 1.13.2 477
- Minigames version: 1.12.1- build # 278 for 1.13 (not latest, but I dont have any spleef minigames so should not affect things)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I originally made the minigames with an update that was a 1.12 build from October and scoreboards were not letting me set them up. Updating to 278 fixed that issue. Could possibly be related to that but unsure if that is relevant info.

Additionally, I have used this plugin for many years and never run into this issue. It may still be a common "did you turn it off then on again" type issue but I am unaware of a fix currently so I'll accept my stupidity if so.

**Comment by Narimm** [comment]
Minigames 1.12 doesn't support paper 1.13 basically with the flattening we cant use id's anymore 
You will need to use a development build
