### ISSUE TITLE
Scoreboard displays "dummy" and doesn't colour the players

### ISSUE THREAD

**Issue by MiniWorks18** [AddstarMC/Minigames#205]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
https://i.imgur.com/EotW7Ic.png

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**

* **What is the expected behavior?**
No "Dummy" on top of the scoreboard, instead the game name. And coloured players.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
- Spigot Version: Paper 1.13.2-481 
- Minigames version: 1.13.0 Build# 278

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Narimm** [comment]
Should have been resolved with commit 55a8f28642b26cd8c7708637e7f4e10c829b7963
