### ISSUE TITLE
Command blocks. And the scoreboard command.

### ISSUE THREAD

**Issue by ThePebblePrince** [AddstarMC/Minigames#206]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [X? ] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
I am unaware if this is a bug. 
But it is isn't then I would like to ask for this feature

* **What is the current behavior?**
All 1.12.2 Scoreboard commands don't seem to work within a minigame. For example.
I have a command block that sets a player to a team using. 
/scoreboard teams join Joined @a[x=-1148,y=8,z=296,rm=0,r=4] <-----
This command will set everyone's team to "Joined" within an area.
But if the player is in a minigame it doesn't set their team to "Joined"

(note- I did change all my command blocks that had /tp commands to /MGM teleport. I don't know if there's a /MGM scoreboard command that works the same way as with Minecraft 1.12.2... I did see the /MGM score command. But I believe that was only for adding score)

This means the command block after that one won't work. 
/MGM teleport @r[team=Joined] -1139 10 305
Along with all the other command blocks that Teleport, Give Effects, Set Score...

I checked and it looks like all the basic /tellraw, /setblock, /clone, /fill.
Are all working properly.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**
All you need to do is /scoreboard teams add TEST. Then /scoreboard teams option TEST color aqua.
This will allow you to press tab and see if your name is the colour aqua. If so then you are apart of that team.

The last step is to put a command block down with the command. (and a button on it)
/scoreboard teams join TEST @p

When you join a mini-game then press the button your name won't be the colour aqua...
And you won't be apart of the team

* **What is the expected behavior?**
For the 1.12.2 Scoreboards to work like the default Minecraft

* **What is the motivation/use case for changing the behaviour?**
All my/other map minigame makers. Mostly know and use command blocks and scoreboards.
I don't know if this will be something hard to fix.

* **Please tell us about your environment:**
- Spigot Version: 1.12.2
- Minigames version: 1.12.0- build #

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Narimm** [comment]
Minigames uses scoreboards to determine which team a player is on during MP games and to ensure people are hidden during SP games and dont collide.  It wont allow you to change the default scoreboard for MG players.
