### ISSUE TITLE
Deaths aren't being mentioned in chat

### ISSUE THREAD

**Issue by MiniWorks18** [AddstarMC/Minigames#207]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [*] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
Currently, there are no messages being put in chat when someone dies or is killed.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**
Create a new multiplayer game. Use two accounts, have one account kill the other. No message is pushed, no stack trace is given. 

* **What is the expected behavior?**
Official minigame message including who killed who.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
- Paper Version: 1.13.2-481
- Minigames version: 1.13- build #281

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Narimm** [comment]
Can I confirm this is ANY message even a direct message to a player v a broadcast?

**Comment by Narimm** [comment]
Outdated build please try the latest and recheck and reopen of still causing issues
