### ISSUE TITLE
Broken link in documentation on Commands Page for "Minigame Tool"

### ISSUE THREAD

**Issue by carrowood** [AddstarMC/Minigames#217]
Bug Report for Wiki, broken link in documentation:

Just FYI, on the Commands page, the 2nd paragraph contains a link to a "Minigame Tool" page. The link is broken.  It goes to:
https://github.com/wiki/Minigame_Tool

It should go to:
https://github.com/AddstarMC/Minigames/wiki/Minigame%20Tool

Keep up the great work.  Love the plugin!

**Comment by Narimm** [comment]
Fixed
