### ISSUE TITLE
How to Assign a loadout to a team?

### ISSUE THREAD

**Issue by cspperson** [AddstarMC/Minigames#22]
I've been testing with your plugin, (it is amazing), and I wanted to make a custom Version of Infected, without the players switching to the infected team. Is there any way that I could do this? Also I wanted to edit the classes that the teams get, and can't seem to find how to do that.

**Comment by skidbld** [comment]
This already exists. The loadout names for presets that use teams are "red" and "blue". If it doesn't work, try using a preset with teams and edit the existing loadouts.
