### ISSUE TITLE
Bug Found

### ISSUE THREAD

**Issue by hstjangdol** [AddstarMC/Minigames#232]
**I found a bug or idk how to called, but when i try to start my minigame aka "Pirates" the server lagged and finally crashed, i know what the problem was, is only happen when i create a regenation area for my minigame, but is not the regeneration at all, i think is the large selection of this, bc i have another minigames with regeneration area and it works, but in my minigame "pirates" that it have a long area, i select the regen area for all my minigame but when i try to start the game, as i said, the server lagged and crashed. and when i re-select the regen area with a little area, the game works again, any solution ? or just i cant use regen area in long selections ?**

**Comment by Narimm** [comment]
To assist with diagnosis: 

You will need to attach the server.log report that contains the error message for us to attempt to review this..also attach the config that causes an error (use pastebin).  If there is no error...please attach a serverlog that shows spigot version/ minigames version and the log file when the issue occurs with `/minigame debug` active

Sincerely
AddstarMC Admin
Please install this plugin http://jenkins.addstar.com.au/job/WhatIs/

**Comment by Narimm** [comment]
Not updated
