### ISSUE TITLE
Can someone on the support team come on my server and help me get started. I have a few things the like lobby, area, and time limit stuff set but it won't start. If a support team member would come on my server xminigamex.minehut.gg to help me that would be great. Please get back to me soon!

### ISSUE THREAD

**Issue by ShoppingMallxD** [AddstarMC/Minigames#243]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report
  - [x] feature request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
- Spigot Version: 
- Minigames version: 1.12.1- build #

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by ShoppingMallxD** [comment]
thank you!

**Comment by Narimm** [comment]
OFF TOPIC PLEASE USE SPIGOTMC for support

**Comment by ShoppingMallxD** [comment]
Where do I put it theN?

**Comment by ShoppingMallxD** [comment]
idk

**Comment by ShoppingMallxD** [comment]
thanks for support
