### ISSUE TITLE
Cannot create teams

### ISSUE THREAD

**Issue by VaporCreep** [AddstarMC/Minigames#248]
Bug report

I enabled the minigames Plugin 2 days ago to use it on my 1.7.10 Server (I use the 1.7 minigame Version). Everything like editing a minigame, adding loadouts, starting the game, using signs etc. works fine, except for one thing. And that is the team creation. The command will not be executed, instead the Chat is showing "an internal error occured executing this command". When I try to make a Team with the minigame menu and write it in the Chat, Nothing happens. And that's a pity because I want to make a minigame for two Teams, currently every Player starts at the same Position. Maybe you know that 'bug' already, I hope there's a solution. I use the minigames-1.7.0.jar with cauldron 1647.201

**Comment by Narimm** [comment]
Sorry Versions below 1.14 are not supported - I am sorry if you want to checkout the branch you can find it here https://github.com/AddstarMC/Minigames/tree/1.7 and submit a patch I will merge and build it but otherwise 🤷‍♂
