### ISSUE TITLE
[Question] Can I cancel block break event in a region?

### ISSUE THREAD

**Issue by xCustomWorld** [AddstarMC/Minigames#257]
I'm making a beacon war thingy like in the "Block Breaking Tutorial", and I wonder if there is any way to protect own team members from breaking the beacon. I have used block break event, and then event to set the beacon back, but this drops the beacon too and it's not really good for performance, as it's server-side thing. I'm using latest dev build for PaperSpigot 1.15.2

**Comment by Narimm** [comment]
Please use the discord channel for support https://discord.gg/xwgKrS
