### ISSUE TITLE
2 issues for FFA

### ISSUE THREAD

**Issue by CrispyWatermelons** [AddstarMC/Minigames#265]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request

Hi, I have created a semi successful FFA mini-game except for some reason even though I have multiple start positions, everyone still spawns on the same one. I have 8 spawn locations and i even used the line command just to make sure. The other bug I'm experiencing in 1.9 is that I have deleted a node for the FFA but for some reason it's still there and every time i go to delete it it duplicates itself. So if possible, I need help Immediately I'll even let you join in a discord call and on my server so someone can help me.

**Comment by Narimm** [comment]
Closed as this is NOT a support channel.  - for godsake read the bloody issue template...IT SAYS DONT USE THIS FOR SUPPORT.
Support here -> https://discord.gg/7kS8NN

**Comment by xCustomWorld** [comment]
I'm willing to jump on your server and check it for you, DM me on Discord: `Kevo#5551`
