### ISSUE TITLE
I like this plugin very much. Can I share it on www.mcbbs.net ?

### ISSUE THREAD

**Issue by HopeGK** [AddstarMC/Minigames#267]
I like this plugin very much. Can I share it on www.mcbbs.net ?

**Comment by Narimm** [comment]
The plugin is opensource - we cant control what you do with it.  That being said you are required to maintain the plugins licencing no matter where you share it.

**Comment by HopeGK** [comment]
> The plugin is opensource - we cant control what you do with it. That being said you are required to maintain the plugins licencing no matter where you share it.

How can I get licencing？
