### ISSUE TITLE
2147483647 score on lives match

### ISSUE THREAD

**Issue by Castiella** [AddstarMC/Minigames#274]
* **I'm submitting a ... **
  - [ X] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

When making a Lives game, the score in game sets to 2147483647. 

Image:
https://i.imgur.com/XQgkYtX.png

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**

Please see config: https://pastebin.com/VydYFeUx

* **What is the expected behavior?**

There to be "lives" with 1?

* **What is the motivation / use case for changing the behavior?**

Just annoying more than anything else

* **Please tell us about your environment:**
- Spigot Version: (Paper Fork)This server is running Tuinity version git-Tuinity-"003c5b3" (MC: 1.15.2)
Though this was also happening on Paper Spigot too.
- Minigames version: 1.12.1- build # Loading Minigames v1.15-SNAPSHOT-315

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by MiniWorks18** [comment]
This is strange and shouldn't happen.
Do you have minigame regions installed? If so, is there a config file I can see?

**Comment by FireInstall** [comment]
As far as I remember, we fixed this bug

**Comment by addstar** [comment]
Closing this - re-open if this is still a problem in the very latest build
