### ISSUE TITLE
spawning people outside of arena

### ISSUE THREAD

**Issue by sudocode1** [AddstarMC/Minigames#276]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
spawning people outside the arena when there are start positions

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**
![image](https://user-images.githubusercontent.com/52894745/80467121-5163fa00-8935-11ea-8cae-2e91260a7098.png)

* **What is the expected behavior?**
they spawn in the arenas

* **What is the motivation / use case for changing the behavior?**
so people can play the game properly

* **Please tell us about your environment:**
- Spigot Version: spigot1649.jar is the file name
- Minigames version: 1.8 the build on the spigot page

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by sudocode1** [comment]
server is cracked btw

**Comment by MiniWorks18** [comment]
This doesn't appear to be an issue anywhere else. It's most likely a problem with your game config. If your minigame is in team mode, make sure you have created your teams in the GUI and that your team spawn locations are set per colour.

**Comment by sudocode1** [comment]
not using teams. it seems to be spawning them at the end/quit pos

**Comment by sudocode1** [comment]
fixed - game config issue
