### ISSUE TITLE
Settings bugs out

### ISSUE THREAD

**Issue by AccioAce** [AddstarMC/Minigames#280]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - Bug Report

* **Do you want to request a *feature* or report a *bug*?**
It's a major bug report, it seems like the minigame settings from loadout keep on resetting after I edited it. The loadout setting resets every time when the sever restarts. 

* **What is the current behavior?**
When the server restarts everytime, the loadout setting resets. 

* **What is the expected behavior?**
I excepted the minigame setting from the loadout not to reset after server restarts. 

* **Please tell us about your environment:**
- Spigot Version: Paper (1.15.2)
- Minigames version: 1.12.1- build #316

**Comment by Narimm** [comment]
Not a bug you cannot edit a config on a running game -the config is resaved on shutdown - either edit the load out in the front end or edit the config in a shutdown state
