### ISSUE TITLE
CTF Minigame deletes after leaving server[BUG] 

### ISSUE THREAD

**Issue by Bienfang1520** [AddstarMC/Minigames#293]
I was making a CTF game and then I left the server I was making it on. Once I joined back it was gone. The sign I set up to join said the game did not exist. But when I do /mg list it was still listed. I tried to rebuild the minigame but each time the same thing happened. It works fine if I don't log off but something must be happening when I log off. Now when I do /mg list 3 CTF show up but I can't join any of them. I have made other games with other presets but only with the CTF preset have I had this issue.

Screenshot of CTF not existing
![image](https://user-images.githubusercontent.com/68299503/87467163-59dedf00-c5cc-11ea-9d37-015449fb21c0.png)

Screenshot of CTF in /mg list
![image](https://user-images.githubusercontent.com/68299503/87467222-75e28080-c5cc-11ea-96e1-c5b69dad77ae.png)

**Comment by Narimm** [comment]
This is not a bug - Please use support discord
