### ISSUE TITLE
[BUG] Unable to add teams to my Multiplayer Minigame

### ISSUE THREAD

**Issue by XBH3Bandit** [AddstarMC/Minigames#296]
**Describe the bug**
I'm currently setting up my first minigame in my server. I'm in 1.7.10 and using the recommended version of the plugin for 1.7 as displayed on the spigot website. Everything was going well until I discovered I was unable to add any teams to my minigame. I have tried both the "/mg edit" and the "/mg set" methods to add teams but it simply refuses to work and my server console gets filled with a mess of errors. Using the /mg set method provides me with a Null error and when I use the gui method I click on add team, the chat asks me for a colour and then when I enter a colour it does nothing and provides me with a "Could not pass event Asyncplayerchatevent" error. Upon a deeper examination of the logs from both errors, they both appear to be caused by "java.lang.NoClassDefFoundError: org/bukkit/scoreboard/NameTagVisibility" and "java.lang.ClassNotFoundException: org.bukkit.scoreboard.NameTagVisibility".

**To Reproduce error
1. use the /mg create command to make a new minigame.
2. use the /mg set command to set the type to multiplayer.
3. use the /mg edit command to enter the gui.
4. click the next page option.
5. click the team options button.
6. click add team.
7. Enter the colour into chat. e.g. RED
alternatively use
8. Enter the command /mg set <minigame> team add <colour>

**Expected behavior**
Upon using the add team option and typing the colour in chat I expected the team of that colour to appear in the team options menu.
Upon using the /mg set method I expected to see the team of the specified colour had been created 

**Screenshots**
* If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via  https://imgur.com/ or similar.
[Asyncplayerchatevent log.txt](https://github.com/AddstarMC/Minigames/files/4984770/Asyncplayerchatevent.log.txt)
[Null command log.txt](https://github.com/AddstarMC/Minigames/files/4984785/Null.command.log.txt)

**Server (please complete the following information):**
  - Prism Version: n/a
  - Server Type: Thermos
  - Server Version: 1.7.10-1614-Server

**Additional context**

**Comment by Narimm** [comment]
While we provide links to older versions we dont provide support or bug fixes you can PR if you want to fix it...

**Comment by Narimm** [comment]
Just to be clear the error is because your not using Spigot - the server your using doesnt follow the Bukkit API an as a result it wont work with the plugin

**Comment by XBH3Bandit** [comment]
I was under the impression that thermos was a meld of spigot, bukkit and cauldron. Is there no way to fix this? I can't update as it would destroy my server since there aren't a lot of options for mods and plugins together.
