### ISSUE TITLE
Add BattleTrackerHook

### ISSUE THREAD

**Issue by orkun1675** [AddstarMC/Minigames#30]
Can you add BattleTracker hook that tells BattleTracker to stop tracking for deaths/kills when a player enters a minigame? It should also tell BattleTracker to resume when they finish/leave the minigame.

I was actually going to do this via a third plugin but couldn't find an API. I have the BT code ready though:

import mc.alk.tracker.Tracker;
import mc.alk.tracker.TrackerInterface;

import org.bukkit.Bukkit;
import org.bukkit.plugin.java.JavaPlugin;

public class Test extends JavaPlugin{

	public static TrackerInterface ti = null;

	public void loadTracker(){
		Tracker tracker = (Tracker) Bukkit.getPluginManager().getPlugin("BattleTracker");
		if (tracker != null){
			ti = Tracker.getInterface("MinigamesHook");
		} else {
			System.out.println("Warning BattleTracker not found. Implemantation disabled.");
		}
	}
	
	public void disableBattleTrackerForPlayer(String playername) {
		if (ti != null) {
			ti.stopTracking(playername);
		}
	}
	
	public void enableBattleTrackerForPlayer(String playername) {
		if (ti != null) {
			ti.resumeTracking(playername);
		}
	}

}

**Comment by skidbld** [comment]
If I am correct, you might be able to get a plugin called PerWorldPlugins. Try that for the moment, and have all your games in one world.

**Comment by orkun1675** [comment]
The plugin you mentioned would solve my issue if I had my minigames on one world and pvp zones on the other. However, I don't.

**Comment by addstar** [comment]
I know this issue is more than a year old (sorry) but with a 3rd party plugin you could hook Minigame events to track when a player joins/leaves a Minigame and enable/disable the BT tracking for that player accordingly.
