### ISSUE TITLE
[BUG] Minigames-1.16-SNAPSHOT.jar

### ISSUE THREAD

**Issue by NikoSenpai47** [AddstarMC/Minigames#300]
**Describe the bug**
I have no idea, something about a ressourse pack

**To Reproduce**
i updated to 1.16 gave me the error instantly
i use Paper 
**Expected behavior**
No errors in the console

**Screenshots**
https://imgur.com/yI5BLz7

**Server (please complete the following information):**
  - Prism Version: not using prism using Minigames-1.16-SNAPSHOT.jar
  - Server Type: Spigot and Paper
  - Server Version: PaperMC-1.16.1.jar

**Comment by Narimm** [comment]
This is a due to a missing zip file you can download and place in the plugin directory from the jenkins server
