### ISSUE TITLE
[BUG]  Plugin ignores kills

### ISSUE THREAD

**Issue by SecretAgent12** [AddstarMC/Minigames#339]
**Describe the bug**

When killing with a weapon committed from Flan`s mod Ultimate(https://github.com/Unknown025/Flans-Mod-Plus) - the plugin does not notice this kill and does not change the points in the scoreboard (mode - FFA).

**To Reproduce**
1.Install the mod - https://github.com/Unknown025/Flans-Mod-Plus
2. Install any content pack (initially the mod does not add anything)
3.start the minigame
4.kill the enemy using any weapon from this mod

**Expected behavior**
When killing a player - the killer's score increases

**Screenshots**
-----

**Server (please complete the following information):**
  - Minigames Version: 1.7.0
  - Server Type: CraftBukkit(Core - Thermos)
  - Server Version: 1.7.10

**Additional context**

Discord of the main developer of the mod - GoldSloth # 0472

**Comment by addstar** [comment]
Sorry but we can't provide support for old versions. The Minigames version you are using is several years old. We only accept issues for current Minigames versions.
