### ISSUE TITLE
Bug: Defeat multiverse using treasure hunt

### ISSUE THREAD

**Issue by wd40bomber7** [AddstarMC/Minigames#34]
Bug:
Player goes to minigame world, a separate world with separate inventory from the spawn world. (Multiverse)

Player acquires items on the minigame world and starts a treasure hunt.

Player logs out. Upon login the player is teleported to the spawn world, and their spawn world inventory is overwritten with whatever inventory they had in the minigames world.

This bug occurs in Events.java:

```
ply.setOfflineMinigamePlayer(new OfflineMinigamePlayer(event.getPlayer().getUniqueId().toString()));
Location floc = ply.getOfflineMinigamePlayer().getLoginLocation();
ply.setRequiredQuit(true);
ply.setQuitPos(floc);

if(!ply.getPlayer().isDead() && ply.isRequiredQuit()){
    Bukkit.getScheduler().scheduleSyncDelayedTask(plugin, new Runnable() {

        @Override
        public void run() {
            ply.restorePlayerData();
        }
    });
    ply.teleport(ply.getQuitPos());

    ply.setRequiredQuit(false);
    ply.setQuitPos(null);
}

plugin.getLogger().info(ply.getName() + "'s data has been restored from file.");
```

Notice, the restore is scheduled for a later time and then the player is teleported immediately. So the player teleports and then the delayed task runs restoring their inventory on whatever world they end up on.

I made a quick patch which looks like this:

```
final Location tpPos = ply.getQuitPos();
Bukkit.getScheduler().scheduleSyncDelayedTask(plugin, new Runnable() {

    @Override
    public void run() {
        plugin.getLogger().info(ply.getName() + "'s data has been restored from file.");
        ply.restorePlayerData();
        ply.teleport(tpPos);
    }
});

ply.setRequiredQuit(false);
ply.setQuitPos(null);
```

I don't understand the reasoning behind the original logic enough to be confident enough to make a pull request. However this does appear to fix the problem.

Strangeness about this section of the code:
Why is it scheduled delayed anyways?
Why move the quit position of the minigame to the LoginLocation? Why does LoginLocation return world spawn?
Why setRequiredQuit(true) and then check if a quit is required?

**Comment by Narimm** [comment]
Can we confirm this is fixed in the dev version @wd40bomber7

**Comment by Narimm** [comment]
Actually looking at the code I am betting the reason you get this error is that you have either NOT set a minigame quit point or you have set it to another world which isnt supported....

To clarify when I player logs out while in a game ... if they are dead OR the game requires they quit on logout then the position when they login is set to the quit position of the game they are playing... 
[onPlayerDisconnect](../blob/master/Minigames/src/au/com/mineauz/minigames/Events.java#L176)

This shows where we set the login location. to be the games quit position.  

```java
@EventHandler
	public void onPlayerDisconnect(PlayerQuitEvent event){
		MinigamePlayer ply = pdata.getMinigamePlayer(event.getPlayer());
		if(ply.isInMinigame()){
			if(ply.getPlayer().isDead()){
				ply.getOfflineMinigamePlayer().setLoginLocation(ply.getMinigame().getQuitPosition());
				ply.getOfflineMinigamePlayer().savePlayerData();
			}
			pdata.quitMinigame(pdata.getMinigamePlayer(event.getPlayer()), false);
		}
		else if(ply.isRequiredQuit()){
			ply.getOfflineMinigamePlayer().setLoginLocation(ply.getQuitPos());
			ply.getOfflineMinigamePlayer().savePlayerData();
		}
```

then on Login

```java
@EventHandler(priority = EventPriority.HIGHEST)
	public void onPlayerConnect(PlayerJoinEvent event){
		pdata.addMinigamePlayer(event.getPlayer());
		if(event.getPlayer().isOp() && plugin.getConfig().getBoolean("updateChecker")){
			long nextCheck = plugin.getLastUpdateCheck() + 86400000;
			if(nextCheck <= Calendar.getInstance().getTimeInMillis()){
				UpdateChecker check = new UpdateChecker(event.getPlayer());
				check.start();
				plugin.setLastUpdateCheck(Calendar.getInstance().getTimeInMillis());
			}
		}
		
		File pldata = new File(plugin.getDataFolder() + "/playerdata/inventories/" + event.getPlayer().getUniqueId().toString() + ".yml");
		final MinigamePlayer ply = pdata.getMinigamePlayer(event.getPlayer());
		if(pldata.exists()){
			ply.setOfflineMinigamePlayer(new OfflineMinigamePlayer(event.getPlayer().getUniqueId().toString()));
			Location floc = ply.getOfflineMinigamePlayer().getLoginLocation();
			ply.setRequiredQuit(true);
			ply.setQuitPos(floc);
			
			if(!ply.getPlayer().isDead() && ply.isRequiredQuit()){
				Bukkit.getScheduler().scheduleSyncDelayedTask(plugin, new Runnable() {
					
					@Override
					public void run() {
						ply.restorePlayerData();
					}
				});
				ply.teleport(ply.getQuitPos());
				
				ply.setRequiredQuit(false);
				ply.setQuitPos(null);
			}
			
			plugin.getLogger().info(ply.getName() + "'s data has been restored from file.");
		}
```

If they can just continue where they logged out for example in a parkour then they are respawned where they logged out.

Finally its a scheduled task because it is not mission critical...ie we dont want to lag the server with it so we schedule it and when the server has a free tick it runs it as soon as possible on the main thread.
