### ISSUE TITLE
Bug with treasure hunt?

### ISSUE THREAD

**Issue by GothkittyGirl** [AddstarMC/Minigames#35]
It worked a while then messed up so i made a new one and worked fine for a while and it messed again and i dont want to redo it again so i left it. It will spawn with nothin in it more often then with stuff in it. not sure if im missing something in the setup but any advice on this would be awesome :)

**Comment by GothkittyGirl** [comment]
i think its is bugged after running to long.. as i just stopped it for a bit then started it again and it spawned with items. no errors in console from what im seeing but i will try this again in future til the issue is fixed

**Comment by Narimm** [comment]
I am not sure what the issue was here but I am closing this off as it is over 2 years old
