### ISSUE TITLE
[BUG] Error when running /mg set (gamename) region select 1

### ISSUE THREAD

**Issue by Skykia** [AddstarMC/Minigames#352]
**Describe the bug**
When running /mg set (gamename) region select 1 command, there is an error and the region isn't selected

**To Reproduce**
Using a server running Paper 1.18.2-234, create a minigame using /mg create (gamename). Then run the command
 /mg set (gamename) region select 1

**Expected behavior**
a region corner would be selected

**Screenshots**
* If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via  https://imgur.com/ or similar.

Here is a screenshot of the console error
https://imgur.com/qpKJx7z.png

**Server (please complete the following information):**
  - Minigames Version: 1.16-SNAPSHOT Build 348 and Minigames-Regions 1.16-SNAPSHOT 348  
  - Server Type: Paper 
  - Server Version: 1.18.2-234

**Additional context**
I tested this on a fresh built server running only the minigames plugin and essentialsX to make sure it wasn't a plugin conflict.

**Comment by FireInstall** [comment]
Should be fixed now.
