### ISSUE TITLE
[BUG] No skulls when using /mg tool select

### ISSUE THREAD

**Issue by Skykia** [AddstarMC/Minigames#353]
**Describe the bug**
When using the command /mg tool select with start positions, end position, quit position or lobby position selected, no skulls appear at the selected points.

**To Reproduce**

Create a minigame with /mg create (gamename)
Create a minigame tool with /mg tool
Set tool to specific minigame with /mg tool minigame (gamename)
Crouch and right click while holding tool to enter menu
Click on Start Positions option
Exit menu and right click to set start positions
Use command /mg tool select while holding tool
A chat messages comes up saying "Selected start points in (gamename)" but no skulls appear on previously set start points.

I've done the above steps for quit position, end position, and lobby position and no skulls appear for those either.

**Expected behavior**
Skulls to appear where points were set

**Screenshots**

**Server (please complete the following information):**
  - Minigames Version: 1.16-SNAPSHOT Build 348 and Minigames-Regions 1.16-SNAPSHOT 348
  - Server Type: Paper
  - Server Version: 1.18.2-234

**Additional context**
The only plugins running on the server are minigames and essentialsX

When the tool has start points selected, right clicking sets the start point, but left clicking the same square brings up a message "Could not find start location at that point." When playing a minigame the start points are functioning as expected, but without the skulls appearing I haven't found a way to remove unwanted start points.

**Comment by Reed022** [comment]
Unfortunately, the only way to remove positions right now is to clear all of them at once:
`/mg set (minigame) start clear` - It's odd, it also sends the help message for it, but it works.

**Comment by Reed022** [comment]
I'm not too sure what you mean about skulls though? Are they supposed to appear as markers? (I've never seen them myself.. so maybe this has been broken for a long time haha)

**Comment by Skykia** [comment]
I've seen skulls and used them to remove start point mistakes in the past but I've been using this plugin on and off since 2014 so I'm not sure specifically when the last time I saw them was. If had to guess I'd say 3ish years ago.

When holding the minigame tool in mode end, quit, or lobby, use the command /mg tool select. The message that pops up is "Selected end/quit/lobby position (marked with a skull)" so there are still messages related to skulls. The skulls were a skeleton head that appeared and sat on top of the block where the selected point was. Right clicking them while holding the minigame tool would remove that point (and the skeleton skull marker)

I'll go ahead and use /mg set (minigame) start clear to cleanup my start point mistakes. Thanks for your help!

**Comment by Reed022** [comment]
Ohhh I see! Okay, I didn’t know about this. I’ll try to look into this though! Thanks for reporting it :)

**Comment by Reed022** [comment]
Oh, if you have a fix, then absolutely, you can open a PR! 🙂
I don’t personally review PRs (in fact, I have a few I’m waiting on haha), and the person who does is busy with 1.18 upgrades on Addstar. So it could be awhile until it’s reviewed unfortunately. But do go ahead and open one.

**Comment by Reed022** [comment]
(Your fix is exactly what I thought it would be too)

**Comment by FireInstall** [comment]
can be closed with the merge of our pull request. It's fixed!
