### ISSUE TITLE
[BUG]  Lock Inventory & Armor in loadouts not getting saved

### ISSUE THREAD

**Issue by R411gun** [AddstarMC/Minigames#361]
The Lock Inventory & Armor option is not getting saved after a server restart
It will revert to false (default state) and needs to be set every time the server boots up

This issue exists since 1.17, tho I haven't created an issue back then as I was not active on github
Issue persists in latest snapshots, even when self compiled

**Comment by joshi1999** [comment]
I guess you can write some Code if you can compile it yourself, so here is quick help:
Take a look in https://github.com/AddstarMC/Minigames/blob/master/Minigames/src/main/java/au/com/mineauz/minigames/PlayerLoadout.java#L491

Change both "lockInventory" and "lockArmour" to "inventoryLocked" and "armourLocked"
Please notice there two lines each which need to be edited. Also only edit these lines in the function load()
If that's completed you can compile and start your server, also the minigames should now load the proper set values.

If you like to participate to this project you can create a pull request with the changed lines

Best regards
joshi

**Comment by FireInstall** [comment]
should be fixed with our pull request being merged.

**Comment by addstar** [comment]
Closing this as this fix will come with a large PR coming soon!
