### ISSUE TITLE
[possible BUG] LivesMechanic float->int conversion is bitwise

### ISSUE THREAD

**Issue by GrigLog** [AddstarMC/Minigames#364]
**Describe the bug**
Scoreboards based on Lives are broken

**To Reproduce**
1) Create any minigame with Game Mechanic "Lives"
2) Enjoy your broken scoreboard

**Expected behavior**
Creating a game with N lives at the beginning should create a scoreboard which displays N points for each player. The displayed score should decrease by 1 with each player's death

**Additional context**
The problem is that Minigames/src/main/java/au/com/mineauz/minigames/mechanics/LivesMechanic.java uses `Float.floatToIntBits` function instead of casting to int. Interestingly enough, initially it worked like it should but this commit from 6 years ago: https://github.com/AddstarMC/Minigames/commit/613c6fb9bd959fe0c62d67d993100b90e6679d82 ruined it for no reason. If you care about representing +inf, -inf and NaN, you could use constants like Integer.MAX_VALUE and INTEGER_MIN_VALUE to represent them. But its not like anyone creates minigames with such weird amounts of lives, everyone just sticks with integers tbh.

**Comment by FireInstall** [comment]
This was fixed in one of our dev brances and we will open a pull request onn (tm)!
