### ISSUE TITLE
Time & lives limit for single player

### ISSUE THREAD

**Issue by MClausz** [AddstarMC/Minigames#38]
The time limit is only for multiplayer, as for the lives limit.
Please make it usable for single player, force player to quit the game when time out or out of lives.
This can be useful for gamemode like parkour or mazes.
Thanks!

**Comment by addstar** [comment]
So if I understand correctly, you'd like to be able to set time limits and life limits on single player games? I'm not sure if this is already possible in our latest dev builds, which version are you using?

**Comment by Narimm** [comment]
Awaiting user update ...1yr closed
