### ISSUE TITLE
Command Blocks

### ISSUE THREAD

**Issue by Infamy11** [AddstarMC/Minigames#42]
Ive gotten an error message "Failed to teleport, this could be related to world permission.:
trouble is, my command blocks work jsut fine outside the plugin.
and theres no regions here at all in my build.
i know this plugin denies all teleports but how about a toggle. in the next update.
the denied commands feature in the config can block teleporting just fine.
doesnt need a global denial of tps...geez.
so i cant use forced tp's in my command blocks for my games and its a bummer.

such as /tp @a[r=44]   which is a teleport all players to one point in a radius command.

which is lame that its denied.
i need a true false perameter if possible...for AllowTeleports true/false. per minigame.
and honestly very suprised that this isnt a perameter already.
i hav the latest build too if your wondering.

**Comment by Infamy11** [comment]
still waiting on feedback....really could use this toggle for something im making. razz can u consider it. a function that lets me use "/tp @a" (all players) to an area?

**Comment by Murreey** [comment]
`/mgm teleport [player] [x] [y] [z]`

@ selectors & relative ~ coordinates are supported.

**Comment by Infamy11** [comment]
thank you murray. this saved my new minigame so much. strange that i didnt spot this in the command list or perm list. was in the process of obtaining a hacked version of this plugin lol...that allows teleporting. thank u again and take care. good luck in your peojects.
