### ISSUE TITLE
Several weird 1.9 issues

### ISSUE THREAD

**Issue by Sharrq** [AddstarMC/Minigames#44]
After updating our server to 1.9 and using the 1.9 Dev Build for Minigames, we are encountering some weird issues. 

Namely, in the minigame i tested with, i would occasionally see the word "null" in the chat box. Usually when something killed myself, so it would look like this

Sharrq was pummeled by Sharrq
null

Additionally, other occasionally vanish and are therefore unattackable. Occasionally they are also invincible, but that seems to only happen if they respawn and dont move (might be on purpose).

Additionally, sometimes killing another player doesnt award points. Sometimes it does, sometimes it doesnt.

**Comment by addstar** [comment]
Sorry for the very late reply.
As mentioned in the issue, I would recommend using our [WhatIs](http://jenkins.addstar.com.au/job/WhatIs/) plugin to find all plugins listening on the PlayerDeathEvent, since these are the only ones that could be causing the issue.
