### ISSUE TITLE
MySQL issue with 1.9

### ISSUE THREAD

**Issue by Murreey** [AddstarMC/Minigames#45]
I updated my server and Minigames to 1.9, and it seems to run fine apart from connecting to and interacting with the remote MySQL database.

The server lags horrifically any time it tries to communicate, and eventually prints an error to the console.

https://gist.github.com/anonymous/531ccf6196abe7aa52e8bacf5a47993a

The errors are slightly different depending on what it was trying to do I guess, but that's the general idea. It's not an issue with connection on the database end, as our 1.8 server is still up and running Minigames 1.8 perfectly fine. I figure it must be a problem with our DB somehow though given nobody else seems to have the issue.

Let me know if you need anything else, thanks in advance!

**Comment by Murreey** [comment]
..turned out it was due to our database having some weird old data from years ago that it didn't like. Works fine after removing all that.

**Comment by addstar** [comment]
This is very strange, glad you got it working though. Out of curiosity was the data minigames related? And if so, which tables and how many rows? Just want to look over to see if there needs to be some MySQL improvements relating to large amounts of data. Thanks.

**Comment by Murreey** [comment]
Yeah, it was Minigames related.

We had a bunch of entries in almost all the tables for our games where the UUIDs had underscores instead of hyphens. They were all players that have been around for a long time, so I assumed it stored them like that for a period before changing or something like that? DB conversion process was failing when it encountered them, but the plugin then just started up anyway and I assume that's what caused the error above.

After I went through and removed all the weird rows, it loaded fine, converted all the data and worked as usual.
