### ISSUE TITLE
Starting Positions

### ISSUE THREAD

**Issue by ChowdyChow** [AddstarMC/Minigames#53]
Okay, When I do /mg set RED (The Minigame I'm Working On) start, i start somewhere else, i've gone into the config file and deleted the one that is making players start somewhere is, but after a while it will come back... PLEASE HELP ME :(

**Comment by Ironic8b498** [comment]
cause you have command wrong;

/minigame set <Minigame> start [player number]
or
/minigame set <Minigame> start <team colour> [player number]

**Comment by ChowdyChow** [comment]
Its a glitch with the minigame tool item...

**Comment by addstar** [comment]
Are you still having a problem or can this be close?

Also be aware that you cannot modify the Minigame config file the server is running. Minigames will re-save all the settings back to the files when the server is shutdown.

**Comment by ChowdyChow** [comment]
Sorry add, looks like it works now... Also not sure how to close a  problem...
