### ISSUE TITLE
Variables/Placeholders

### ISSUE THREAD

**Issue by trevor1097** [AddstarMC/Minigames#55]
Are there placeholders that can be used for making game menus or could you hook into Placeholder API?
 [https://www.spigotmc.org/wiki/hooking-into-placeholderapi/](url)

**Comment by addstar** [comment]
Unfortunately not, and we don't have any plans to add these currently.
We would be happy to review a PR if someone would like to add these to the plugin, but it's not a feature we need for our own server and sadly we don't have time to add features we won't use. We have too many other priorities taking our time currently.
