### ISSUE TITLE
Hunger don't deplete

### ISSUE THREAD

**Issue by Ironic8b498** [AddstarMC/Minigames#57]
I have been working on this issue for about  a year off an on, I made a second PVP min game and it has same issue, no matter what I try the hunger bar will not go down.

**Comment by addstar** [comment]
Sorry for the delay in replying, are you still having this issue?
It may be caused by another plugin (eg. WorldGuard) or possibly you have disabled the "Allow Hunger" option in the load out?

You also didn't provide the Minigames plugin version you are using and the version of spigot.

**Comment by Narimm** [comment]
Need more information.  Reopen if you wish to provide more info.
