### ISSUE TITLE
Starting

### ISSUE THREAD

**Issue by mitchyb99** [AddstarMC/Minigames#58]
Hello, when I set this all up, my game wont start. It counts down to 5 then stops. Just keeps saying 5, 5, 5. Also, when I restart the server, the loadouts go away.

**Comment by addstar** [comment]
Which version of the plugin are you using and which Spigot version? We need a lot more info than this, sorry. Can you also tell me info about the game you set up?

**Comment by redstoneengie** [comment]
acctually i have the same problem with it too and the version is 1.8.0 version

**Comment by Caelum100** [comment]
I have this problem too. I am using Spigot for Minecraft 1.10 and the latest version of Minigames from Curse.  I set up a multiplayer deathmatch style game.

**Comment by Narimm** [comment]
I strongly suspect this is a config issue .  I it appears this happens while waiting for players.
I would suggest posting configs to the Spigot discussion for help there or look at the wiki.

We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC
