### ISSUE TITLE
Bug: Scoreboard names not visible

### ISSUE THREAD

**Issue by orkun1675** [AddstarMC/Minigames#59]
Because our players have name prefixes, the scoreboard signs cannot display their actual nickname but their prefix only. Can we add an option to display the nickname only and not the long player name (with the the prefix) on scoreboard signs?

**Comment by orkun1675** [comment]
Opened a pull request for this #62

**Comment by addstar** [comment]
Please see comments on #62 - This should fix your issues if implemented.
