### ISSUE TITLE
Bug: MySql Tables for MiniGame Stats are not re-created after deletion

### ISSUE THREAD

**Issue by orkun1675** [AddstarMC/Minigames#61]
Is there a work around for this?

**Comment by addstar** [comment]
Can you explain what you mean and describe the situation? I'd prefer more than just a single sentence :wink: 
Thanks.

**Comment by Narimm** [comment]
I think he means that the mysqlBackend doesnt recreate the db if its not present...the sqlitebackend does..
[SqlLite version here](https://github.com/AddstarMC/Minigames/blob/523983d5dba5d5efb96b31546cecb9d57eb5177e/Minigames/src/au/com/mineauz/minigames/backend/sqlite/SQLiteBackend.java#L98)

Mysql doesnt have an equivalent version

**Comment by Narimm** [comment]
In reviewing the code base the Minigame should recreate the PlayerStats table if it doesnt exist...
