### ISSUE TITLE
Saving Player Creations in a world

### ISSUE THREAD

**Issue by CausticLasagne** [AddstarMC/Minigames#64]
I've got Minigames running my creative world to sandbox the creative inventory from the survival inventory, and so far it works, but I need minigames to not delete blocks that the player has built.

Is there any way I can achieve this?

CausticLasagne.

**Comment by Noket** [comment]
Hi.. From what I've seen, it's not possible. I would recommend just using
plots created with worldguard, then use perworldinventories (plugin) to
prevent players from keeping inventories from your creative world in other
worlds

**Comment by CausticLasagne** [comment]
Ok, since writing this message, I've been poking around in the Minigames Code and found this:
`mgm.getBlockRecorder().restoreBlocks(player);`
`mgm.getBlockRecorder().restoreEntities(player);`
in SingleplayerType.java (Ln 103, 104).

I was thinking about forking your plugin with a custom flag to disable these restore functions. It will massively help my server, and enable new types of minigames to be made.

If you can implement this for future builds, that would be awesome, but I'll try the Worldedit + perworldinventories to see if it works.

The only issue with PerworldInventories is that it only needs to seperate the creative world and the survival worlds (hence why per world would not be ideal). creative is only 1 world.

Anyways, Cheerio.

**Comment by Noket** [comment]
A better option might be too use composition to extract the changing
behavior. Define an interface "CleanupBehavior" with the method cleanup().
Then define two classes that implement CleanupBehavior: "NoBlockRestore"
and "BlockRestore".

CleanupBehavior cleaner = new NoBlockRestore(params);
CleanupBehavior cleaner = new BlockRestore(params);

Then, just replace the offending code with.. cleaner.cleanup(). Use the
game type to determine which cleanup behavior should be used

**Comment by addstar** [comment]
@CausticLasagne sorry for the delay in responding. So if I understand correctly, you want the ability to disable the change rollback when a Minigame ends? Sounds like it could be a useful feature for others. Feel free to fork and add the feature and we'd happily review a Pull Request if you like? Be aware it would need to have a toggle in the GUI to be accepted.

@Noket thanks for the helpful comments/ideas, we appreciate the community involvement! :+1:
