### ISSUE TITLE
Rewards Issue

### ISSUE THREAD

**Issue by ToonyMann** [AddstarMC/Minigames#65]
Hello, I've been using Minigames 1.8.0 with my Spigot 1.8.8 server.

I've done several tests and i actually have 6 minigames already created. They work great but none of them has any rewards when you finish them.

During my tests i've noticed that only the first time that you play the game you can have a reward, a diamond by default. But if you try again you don't receive anything.

I tried looking in the config files and database but i cannot find what could be the problem. The console don't throw any error.

What can i do to resolve this?

Thank You. Wonderful plugin.

**Comment by addstar** [comment]
Hi @ToonyMann, in Minigames you can set primary+secondary rewards.

Primary reward = when the player wins that Minigame for the first time
Secondary reward = when the player wins that Minigame any time after that

You might not have the secondary reward set on your Minigames, please check this in the `/mg edit` GUI

Thanks.
