### ISSUE TITLE
CTF Capture on any flag

### ISSUE THREAD

**Issue by Thyestefles** [AddstarMC/Minigames#66]
Hello,

I just started setting up CTF games again using the latest dev build. While testing, I noticed that I could capture the other team's flag on any flag of my own color. The capture point works as well as the flags themselves, for capturing. While the game still functions, this poses some problems for creating strategic layouts if players can capture on any flag of their color. 

Say I want to put a flag close to enemy territory that requires higher defense. Personally, I would like to do that without having that point become a capture point. If this is intended, however, I can figure out a way to work around it.

This line in the CTFMechanic class, at line 151, seems to be what is allowing this to happen. The other two options require that the flag contain the text "Capture".

else if(team == TeamsModule.getMinigameModule(mgm).getTeam(TeamColor.matchColor(ChatColor.stripColor(sign.getLine(2)))) ||

**Comment by Narimm** [comment]
So if I understand correctly you want to stop a team being able to use thier own flag as a capture point?

**Comment by Narimm** [comment]
THis is Fixed in the latest development build by the commit above you can get the version 
http://jenkins.addstar.com.au/job/Minigames/168/[http://jenkins.addstar.com.au/job/Minigames/168/](url)
