### ISSUE TITLE
the countdown in the lobby "5sec 5sec 5sec 5sec"

### ISSUE THREAD

**Issue by redstoneengie** [AddstarMC/Minigames#67]
hi i have recently installed yur amazing plugin for capture the flag and well i wanna start a game for a test and it goes 10sec then 5sec the 4sec but constantly goes 4sec NEVER ENDING and its a real pain in the ass can u tell me what im doing wrong or is it a bug u need to fix? pls get bck to me if u know im doing something wrong this is a SERIOUS MATTER! PLS REPLY BACK!!! #58

**Comment by redstoneengie** [comment]
here is proof too

![bandicam 2016-11-05 21-25-30-098](https://cloud.githubusercontent.com/assets/23281960/20033680/66eddb78-a39e-11e6-8ec4-d68805e9e34a.jpg)

**Comment by Caelum100** [comment]
This happened to me too. I am running Spigot for Minecraft version 1.10 and the latest version of Minigames plugin. The minigame I tried to create was a multiplayer deathmatch, but the countdown stays at 5 seconds.

**Comment by redstoneengie** [comment]
forget this plugin if these people cant do it properly may aswell go to "the war" plgin it has loads of stuff as well as ctf and no countdown time just puts u into the map and it has a proper flag not just a stupid sign and u can have TNT and if i makes a mess when the match is over it resets the map like it was before u started!!!

**Comment by addstar** [comment]
@redstoneengie sorry for the delay in getting back to you. We need more information than that to diagnose this:

- Exact server version
- Exact Minigames version (don't just say "latest")
- Do you have any errors in console? (this is very likely and critical to solving this)

Also, on a side note, Minigames can handle TNT, reset maps each time the game plays, has a save/restore "backup" for admins, countdown timer works perfectly fine on all the 30+ Minigames on our server (and hundreds of other servers).

**Comment by Narimm** [comment]
We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC
