### ISSUE TITLE
Lobby countdown stuck at 5 seconds

### ISSUE THREAD

**Issue by Caelum100** [AddstarMC/Minigames#68]
I am trying to set up a free-for-all deathmatch type minigame. I have a lobby position, start positions, and end and quit positions. Sadly, the game countdown is stuck at 5 seconds and repeats it when in lobby with multiple players. I am using Spigot for Minecraft 1.10.2 and the most recent version of Minigames plugin.

**Comment by Narimm** [comment]
See issue #58 

We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC

**Comment by Dovydasr** [comment]
When I start the FFA game on my server my friends or me gets teleported to the end position or quit position (it's same spot). How can I fix this problem?
