### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AccioAce** [AddstarMC/Minigames#69]
Sorry Razz I got question :D I was wondering will this plugin ever update to 1.11 since 1.11 coming out. Because I would love to use this plugin. Is my most favorite plugin. 

Thank You!

**Comment by addstar** [comment]
Yes, this plugin will definitely be updated to 1.11 (soon!). But Razz isn't working on it any more.

The plugin is now maintained by [AddstarMC](http://addstar.com.au/) and the project page is [here](https://www.spigotmc.org/resources/minigames.19687/).

The update will be out soon, don't worry :)
