### ISSUE TITLE
Minigame GUI Bug

### ISSUE THREAD

**Issue by midnightmythix** [AddstarMC/Minigames#70]
Whenever you open the gui by either using the minigame tool or /minigame set , if you decide to go into another gui (for example, use the minigame tool to go the the second page) it acts as a normal chest and when you click on things it doesnt execute anything.
Therefore,
I cant make loadouts and stuff like that.

**Comment by addstar** [comment]
This means you have a plugin conflict. Some other plugin is handling inventories events and most likely not considering other plugins. You should try testing this by removing plugins one by one to find which one is causing the issue. Or run it on a new/clean server install.

You can also use the [WhatIs plugin](http://jenkins.addstar.com.au/job/WhatIs/) to find which plugins are listening on Inventory events.

If you're still having the problem after that, please tell us the exact server version, Minigames version and the plugins you have on your server.
