### ISSUE TITLE
1.11

### ISSUE THREAD

**Issue by PugaBear** [AddstarMC/Minigames#71]
I've just updated to 1.11 on my test server and Minigames...explodes.

It first repeats [this error](http://paste.bn-mc.net/pirer) for all of the existing game configs, then repeats [this error](http://paste.bn-mc.net/ojiru) about the same amount of times as the first error.

**Comment by addstar** [comment]
Hi @PugaBear, Minigames is not yet compatible with 1.11.
We are working on releasing a 1.11 version soon, unfortunately I don't think there's anything you can do to make that work for you in the mean time.
