### ISSUE TITLE
 Task #24 for Minigames v1.7.0 generated an exception

### ISSUE THREAD

**Issue by Glamhammer** [AddstarMC/Minigames#73]
My timer gets stuck at 5 seconds and when starting it gets stuck again at 3 seconds, I get this message on my console WARN: "Task #24 for Minigames v1.7.0 generated an exception" or the "java.null.pointer...." I can remember the whole error it stated. I am running this on 1.11.2 [Latest Version] of Minecraft.
This is basically what it says:28.12 22:45:32 [Server] WARN Task #25 for Minigames v1.7.0 generated an exception
28.12 22:45:31 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
28.12 22:45:31 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [CraftBukkit.jar:git-Bukkit-0fb3f8b]
28.12 22:45:31 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [CraftBukkit.jar:git-Bukkit-0fb3f8b]
28.12 22:45:31 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [CraftBukkit.jar:git-Bukkit-0fb3f8b]
28.12 22:45:31 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:689) [CraftBukkit.jar:git-Bukkit-0fb3f8b]
28.12 22:45:31 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [CraftBukkit.jar:git-Bukkit-0fb3f8b]
28.12 22:45:31 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[CraftBukkit.jar:git-Bukkit-0fb3f8b]
28.12 22:45:31 [Server] INFO at au.com.mineauz.minigames.MultiplayerTimer$1.run(MultiplayerTimer.java:83) ~[?:?]
28.12 22:45:31 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class au.com.mineauz.minigames.sounds.MGSounds
I am running a ctf game. Your help would be very much appreciated since this is the only problem I am having before opening my server.

**Comment by jupiter1390** [comment]
Whoa you are using old version
Using DevBuild Version should fix that error
http://jenkins.addstar.com.au/job/Minigames/

**Comment by addstar** [comment]
@Glamhammer Yeah, you definitely need to be using the latest dev builds. The 1.7 series is not compatible with 1.8+

We aren't very good at maintaining the spigot project page.. we just don't have time any more :(

**Comment by addstar** [comment]
FYI: Please see this page https://www.spigotmc.org/resources/minigames.19687/
