### ISSUE TITLE
Cannot create Infection

### ISSUE THREAD

**Issue by CurtainHumper** [AddstarMC/Minigames#75]
I can't seem to create an Infectiontype minigame. I have done everything as told, tried multiple ways, but it still won't work. The present won't work either.
Sometimes my players get teleported straight to the end/quit positions, eventhough I made startpositions.
Please help me.

**Comment by Narimm** [comment]
This forum is really for bug reports and errors...I would suggest using the Spigot forum to get help from other users regarding configuration isses
