### ISSUE TITLE
Disable Tab List

### ISSUE THREAD

**Issue by KevinEssence** [AddstarMC/Minigames#76]
We have plugins that modify name tags..everytime players start an infection game it changes their names in the tab list..score board is fine..and after the game ends there names are white and it creates a ugly tab. Anyway to disable team game modes to not modify tab names and just leave them be like the other game modes?

**Comment by Narimm** [comment]
Unfortunately Spigot does update the tab list based on  a scoreboard...what I have / am doing is changed the way players are added to a scoreboard ie we are no longer going to use the deprecated spigot api and use the new String sets...not sure if this will fix your issue or not!
