### ISSUE TITLE
Problem with node do console cmd 

### ISSUE THREAD

**Issue by cboy116** [AddstarMC/Minigames#78]
So let me first say i love your plugin, especially the node/region system. However i have come to a fatal flaw. When i use the server cmd action there is no placeholder in order to put the player who triggered the nodes name. This makes it almost impossible to use this to trigger other player specific cmds for custom game behaviors. Adding a simple placeholder would add so much flexibility! Thanks for reading.

**Comment by cboy116** [comment]
Just read through that section of the code. You already have this implemented 👍, i would recommend adding this to the docs so that people know without reading the code.

**Comment by Narimm** [comment]
No probs we encourage people to update the info here 
http://mgwiki.addstar.com.au/
