### ISSUE TITLE
[question] high CPU usage?

### ISSUE THREAD

**Issue by RealmportalMC** [AddstarMC/Minigames#79]
is it normal for this plugin to significantly increase the CPU load?
after installing it it seems that CPU Usage has gone up from 5 - 10%  all the way to 20 - 30%

no new error messages are showing up in console after installing either.

forgot to mention that we have 47 other plugins. Except CPU is higher now.

**Comment by Narimm** [comment]
We have never heard of this before...run spigot timings maybe and check what is running a lot. ??
