### ISSUE TITLE
minigame score error + region/node teleport tag bug?

### ISSUE THREAD

**Issue by jupiter1390** [AddstarMC/Minigames#80]
It the minigame's minscore and maxscore is both 5
and player gets score by region/node, score is added but minigame won't end the minigame properly, maybe it has error about reading score added by region/node

+region/node teleport tag wouldn't work properly

**Comment by Narimm** [comment]
Sounds like a config issue...please use the spigot forums

If you have an actual bug report please feel free to reopen

**Comment by Narimm** [comment]
We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.
We monitor this thread as well, as do other users of the plugin.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC
