### ISSUE TITLE
Teleporting

### ISSUE THREAD

**Issue by RedJambo123** [AddstarMC/Minigames#82]
I know that you have disabled teleporting, due to the potential of people taking items out of the game and teleporting to places that they shouldn't, but I'm trying to create a game where the use of multiverse portals is essential. Is it possible that you could make it toggleable? I'm using the Dec build for 1.11 and everything else seems to work fine. In the mean time if I set Allowteleport to true in the players class file will that allow me to use multiverse portals?

**Comment by RedJambo123** [comment]
I must also mention that they won't be teleporting between worlds but to somewhere within the same world. It's for the CTF game mode, where teams spawn in a room and then use mvp to teleport to a random location within their flag area to prevent spawn camping. And doing it that way would look so much cleaner that having loads of teleport signs filled with coords.

**Comment by Narimm** [comment]
Typically we design a spawn area that might be a platform 2-3 blocks above the home area of the base.  It has walls so they cannot use it as a arrow platform etc and then a 3 narrow drop down area with a ladder from it so you cant camp it really

Random teleporting could be something we could do using a minigame region

**Comment by RedJambo123** [comment]
Thanks very much for the suggestion :D unfortunately I am unable to create the platform due to the way the play map is already built. We are expecting around 200 players for this particular game. Basically what I'm looking to achieve is to have players teleport into a sealed room where they will be able to choose a loadout and then they enter a portal which teleports them to a random location within their area of the map. The way I tried with mvp is, I created 8 portal locations around the players start area and then use the random teleport feature of multiverse (not documented) to tp the players to one of those defined portals. The command to do this is /mvp create <portal>:<p1>:<p2>:<p3>

I would be more than happy to help with input, just let me know what sort of things you would like to know :D

**Comment by RedJambo123** [comment]
If you would like, I'm happy to whitelist you on the server so you can get a better visual of what I am talking about? It's currently not open to players yet, but it is due to have a few testing players join on the 12 Feb with the event taking place on the 18th

**Comment by RedJambo123** [comment]
I'd like to note that I sorted this issue by creating a region that when players enter it runs a server command that does a spread players command.

**Comment by Narimm** [comment]
Interesting - thanks Red

I was thinking we might add a new feature that allows you to specify a sign based teleport that will bypass the teleport restrictions but also make teleporting availabe or toggleable
