### ISSUE TITLE
minigame score error when score is added by node and regions(Not a configuration error)

### ISSUE THREAD

**Issue by jupiter1390** [AddstarMC/Minigames#83]
If a score is added by node and regions, minigame won't finish if a user gets score more than min/max score
For example, if the minigame's min/max score is both set to 3 and If I obtain 1 score by using node and region, It wouldn't finish the game even my score is 3, but it still finishes when I obtain score not using node and region like killing a player in kill mechanic.

+region/node teleport tag wouldn't work properly

Not a configuration error, It's a bug

**Comment by Narimm** [comment]
Can you post a config of the game or outline exactly what you have configured...this is sounding more like a bug that allowed a config that shouldnt be allowed

**Comment by jupiter1390** [comment]
for normal config:
비행레이스:
  loadouts:
    default:
      items:
        '102':
          ==: org.bukkit.inventory.ItemStack
          type: ELYTRA
        '8':
          ==: org.bukkit.inventory.ItemStack
          type: FIREWORK
          amount: 64
          meta:
            ==: ItemMeta
            meta-type: FIREWORK
            display-name: §f추진기
  gameOver:
    timer: 10
    humiliation: true
  reward-scheme: standard
  rewards: {}
  reward:
    '0':
      type: MONEY
      rarity: NORMAL
      data: 5.0
  reward2:
    '0':
      type: MONEY
      rarity: NORMAL
      data: 5.0
  minscore: 3
  type: MULTIPLAYER
  endpos:
    x: 0.5
    y: 65.0
    z: 0.5
    world: lobby
    yaw: 0.0
    pitch: 0.0
  allowMPCheckpoints: true
  lobbypos:
    x: 10.948912000308399
    y: 21.0
    z: -109.00041922085889
    world: MG_basic
    yaw: -90.60773
    pitch: -0.2999955
  maxplayers: 8
  flags: []
  maxscore: 3
  enabled: true
  startpos:
    '0':
      x: 38.497021281688525
      y: 22.0
      z: -123.46777756583018
      world: MG_basic
      yaw: 188.24332
      pitch: 12.599976
    '1':
      x: 40.41221117419467
      y: 22.0
      z: -123.4326723258446
      world: MG_basic
      yaw: 180.14331
      pitch: 4.200018
    '2':
      x: 42.60928265580023
      y: 22.0
      z: -123.50543122314646
      world: MG_basic
      yaw: 181.49333
      pitch: 8.999971
    '3':
      x: 44.57732388028791
      y: 22.0
      z: -123.47472562694254
      world: MG_basic
      yaw: 179.84326
      pitch: 12.449996
    '4':
      x: 46.55433719277352
      y: 22.0
      z: -123.58379145402424
      world: MG_basic
      yaw: 176.24335
      pitch: 13.200016
    '5':
      x: 48.53715259103575
      y: 22.0
      z: -123.63462484032767
      world: MG_basic
      yaw: 172.94339
      pitch: 12.150003
    '6':
      x: 50.45734589227377
      y: 22.0
      z: -123.56017966334905
      world: MG_basic
      yaw: 169.34341
      pitch: 12.449983
    '7':
      x: 52.44722320408437
      y: 22.0
      z: -123.55155914072314
      world: MG_basic
      yaw: 165.59337
      pitch: 10.649997
  timer: 180
  quitpos:
    x: 0.5
    y: 65.0
    z: 0.5
    world: lobby
    yaw: 0.0
    pitch: 0.0
  scoreboards: {}



for region config:
비행레이스:
  regions:
    Bottom:
      point1:
        world: MG_basic
        x: -65.0
        y: 4.0
        z: -194.0
      point2:
        world: MG_basic
        x: 64.0
        y: 15.0
        z: -66.0
      executors:
        '0':
          trigger: ENTER
          actions:
            '0':
              type: VELOCITY
              arguments:
                xv: 0.0
                yv: 1.0
                zv: 0.0
    End:
      point1:
        world: MG_basic
        x: 31.0
        y: 4.0
        z: -122.0
      point2:
        world: MG_basic
        x: 64.0
        y: 25.0
        z: -119.0
      executors:
        '0':
          trigger: ENTER
          actions:
            '0':
              type: ADD_SCORE
              arguments:
                amount: 1
            '1':
              type: REVERT
          isTriggeredPerPlayer: true
        '1':
          trigger: ENTER
          actions:
            '0':
              type: END
          conditions:
            '0':
              type: PLAYER_SCORE_RANGE
              arguments:
                min: 2
                max: 3
                invert: false
          triggerCount: 1


other minigames without regions work nice, though

**Comment by jupiter1390** [comment]
@Narimm is this bug fixed?

**Comment by Narimm** [comment]
So the trigger for ending a game on entry of a region is not called END its GAME_END try that

**Comment by jupiter1390** [comment]
@Narimm
It works with end tag, though

+ The main point is every minigame with score added by region&node won't end even they reached minscore, but they would end if score is reached by minigames' basic configuration like killing other
This is serious bug

**Comment by Narimm** [comment]
I am sorry but I dont understand the bug...you you forced it to end using region. It would not work with region? That is contradictory

**Comment by jupiter1390** [comment]
@Narimm
If score is added by region&node, minigame won't end even user reached minscore to win

**Comment by jupiter1390** [comment]
@Narimm
I give example becausw this bug is hard to explain

If there is a kill mech minigame that has minscore and maxscore 5 so you should win if you reach score 5
And that minigame has region&node tag that makes user get score 3 when entering specific region

If user reach score 5 by kill, minigame would end automatically.
But, if user reach score 5 by 2 kill and 3 by entering region, minigames won't end automatically

I think the problem is minigame would calculate whether user reached minscore or not ONLY when the score is obtained by basic mech-based ways

**Comment by Noahkiq** [comment]
I believe this is fixed in a recent version?

**Comment by Noahkiq** [comment]
This was fixed around a month ago... pls close
