### ISSUE TITLE
Need help with teams loadouts

### ISSUE THREAD

**Issue by Byroncoco** [AddstarMC/Minigames#86]
Ok, so I want to make it that each team has different armour as default. I wand to be able to have 1 default loadout for say red team and a different default loadout for the other. 

Thanks in advance 👍

**Comment by Narimm** [comment]
Please use the Spigot MC forums for configuration issues this is for bugs only

**Comment by Narimm** [comment]
We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.
We monitor this thread as well, as do other users of the plugin.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC

**Comment by Byroncoco** [comment]
Ok, sorry. 

I was told on mineccraft forums to post here.

**Comment by Narimm** [comment]
which forum I need to go and remove that directive

**Comment by Byroncoco** [comment]
Don't worry, I have gotten rid of it. I asked the question and someone told me to do that.

BTW I asked to same question on the spigot discussion list now.
