### ISSUE TITLE
(bug) Snowballs keep building up in inventory on infinite ammo paintball mode

### ISSUE THREAD

**Issue by RealmportalMC** [AddstarMC/Minigames#88]
Whenever I set Paintball mode to true, set infinite ammo to true and give players snowballs, they throw them, but more than i orignally gave go into their inventory.

IE: I give 1 snowball in a kit and then a player spam throws it, there will be 2 3 4 5 6 7 8 snowballs etc.
When it reaches 16, it starts a new stack. Build 168 - spigot 1.11.2

**Comment by Fordy436** [comment]
Snowballs don't do damage set in settings - They act like normal snowballs.

**Comment by Narimm** [comment]
With no further reporting and atleast
