### ISSUE TITLE
useSSL=false

### ISSUE THREAD

**Issue by PugaBear** [AddstarMC/Minigames#90]
![image](https://cloud.githubusercontent.com/assets/12417961/24017176/fa373c88-0a5c-11e7-908a-59ba616e63f0.png)

**Comment by txgs888** [comment]
Add it to the back of the password `&useSSL=false`
May be able to solve your problem xD
`backend:`
`  type: mysql`
`  host: localhost:3306`
`  database: database`
`  username: username`
`  password: password&useSSL=false`

**Comment by Narimm** [comment]
Yep I think Ill go for a better solution and add connection properties 

see 
http://stackoverflow.com/questions/34189756/warning-about-ssl-connection-when-connecting-to-mysql-database
