### ISSUE TITLE
Old configuration not supported

### ISSUE THREAD

**Issue by TNTUP** [AddstarMC/Minigames#92]
Hey, I've updated to the latest dev build #169 and I have a looot of minigames set and the console gets spammed every server reboots https://hastebin.com/zimoducope.css

I can't redo them because theres too many of them, hoping if a converter is possible.. Downgrading fixes it but well... Minigames are working as normal no problem at all but everytime I get spammed by this error. Can it be safely ignored?

**Comment by jupiter1390** [comment]
Why don't you remove minigame scoreboard sign part from yml file of each minigame?
I suffered similiar error with you and removed all scoreboard sign tags, and it worked!

**Comment by TNTUP** [comment]
@jupiter1390 Ooh nice to know that! Will do and thanks if it really do work!

**Comment by Narimm** [comment]
This was a known problem we wont be fixing scoreboards changed with the new version

**Comment by TNTUP** [comment]
@jupiter1390 I have removed them and they're still there (I have deleted them in all minigames!) and when I've started up the server they came back!

I don't use such scoreboard signs, but in the minigame the scoreboard is visible (as normal) or you mean those (minigames) <arenaname> causes this?

**Comment by Narimm** [comment]
Can you please add a copy of the 
1. Server log on start up
2. config

**Comment by TNTUP** [comment]
Hi, herre's the complete startup log https://i.qcfb.ca/20170517011313.txt (Ignore the ASkyBlock errors, just started it for the first time upgraded a previous version. You'll see that kind of error "[Minigames] Your configuration files () are of an old version. They will not be supported past ver1.11".

Config file is here: https://i.qcfb.ca/config.minigames.20170517.yml (Note this config got never regenerated, do I need to do that?)

I have 120+ minigames, and pasting them all here can be an hassle or else downloading them all and zipping 'em XD

**Comment by Narimm** [comment]
I have removed the warning for now...tbh I cant remember why I added it....latest build should do it....
