### ISSUE TITLE
Using playername as a parameter in reward commands

### ISSUE THREAD

**Issue by agentroop** [AddstarMC/Minigames#93]
I want to run a command that will give players a different kind of currency on my server according to a plugin. The command would be run like this:
/notes give <player> 100.

However, I don't know what string to use to represent <player> for this configuration. Is this possible with the command setting?

**Comment by addstar** [comment]
Hi,
When you use the string `%player%` in a command reward, it will replace it with the winning player's name. Unfortunately the wiki hasn't been updated in a long time and this isn't mentioned on the wiki.

**Comment by jupiter1390** [comment]
@add5tar Is there any other string variables
