### ISSUE TITLE
Ability to hide team message

### ISSUE THREAD

**Issue by PugaBear** [AddstarMC/Minigames#94]
I'm coding my own gamemode using the API, and would like to hide the messages that are displayed at the start ([this one specifically](https://github.com/AddstarMC/Minigames/blob/master/Minigames/src/au/com/mineauz/minigames/minigame/Team.java#L117)) so that I can determine the player's team myself. Adding the ability to hide the message from line 118 in that file would also be helpful

**Comment by Narimm** [comment]
I'll be honest we havent looked at the API in about 2 years...and I am unlikely to do so...in the short term.
