### ISSUE TITLE
Multiplayer spawnpoints doesn't work

### ISSUE THREAD

**Issue by Axlnh** [AddstarMC/Minigames#96]
Hello, thanks for this awesome plugin :)
When I create an arena and I setup a lobby, spawnpoints etc. the multiplayer mode keeps teleporting me to the lobby (like normal use) and then to the point where I did "/mg create ARENANAME multiplayer".
Perhaps, in singleplayer it bypass the lobby so I can't choose a loadout and spawn points work.
Any idea ? 
Thanks in advance !

**Comment by jupiter1390** [comment]
Just use
/mg set ARENANAME mutiplayer
this always work though

**Comment by Axlnh** [comment]
Thanks for your answer.
I tried but it only does this : http://prntscr.com/f11evy
It doesn't apply the command to the arena

**Comment by jupiter1390** [comment]
@Axlnh
oh srry i typo
/mg set ARENANAME mode multiplayer

**Comment by jupiter1390** [comment]
@Axlnh
/mg set ARENANAME type multiplayer

**Comment by Axlnh** [comment]
It is still not working :/
Btw when I suicide the spawn works, but I always need to suicide once

**Comment by jupiter1390** [comment]
@Axlnh
Why don't you try killing people using region&node at first participation?
like execute "kill" on entering region, triggered once and triggered per player.

**Comment by Narimm** [comment]
Ok so this is not a support forum its for Bug reporting Spigot forums are for config issues...

**Comment by Axlnh** [comment]
It's not a config issue since everything is normal in the config.
It's a problem with the plugin.

**Comment by Narimm** [comment]
Sorry but just because a plugin wont do something you want it to do doesnt make it a bug...at best its an unimplimented feature.
