### ISSUE TITLE
Allow AutoBalancing of teams to be configurable.

### ISSUE THREAD

**Issue by Narimm** [AddstarMC/Minigames#97]
Many are asking to have the ability to disable autobalancing.

To achieve this we will add  a new teamflag that is switchable to enable/disable autobalance on a team basis.

**Comment by jupiter1390** [comment]
Can you also add better autobalancing like this:
If there are two teams and have odd number players, dead player would switch to other team for balance

**Comment by Narimm** [comment]
It already does that

**Comment by Narimm** [comment]
And no I am not making it so that if one team has 5 and the other 4 and one of the team of 5 dies they get switched thats just annoying
