### ISSUE TITLE
I suggest to show players on the Join sign. The players playing.

### ISSUE THREAD

**Issue by LinsaFTW** [AddstarMC/Minigames#99]
It would make this plugin worth it... No one was playing because of that... They didnt know where players was

**Comment by Narimm** [comment]
There is already the capability to show the number of players in a game on a sign

**Comment by LinsaFTW** [comment]
@Narimm Hi, can you tell me how please? Im going to use this plugin back again because i switched to 1.12.

I readed the wiki and it doesnt say anything about showing the player count in the join sign.
